import type { ThemeId } from "../../utils/themes";

export const es: Record<ThemeId, string[]> = {
  animals: [
    // 3-letter
    "AVE",
    "BOA",
    "OSO",
    "PEZ",
    "YAK",
    // 4-letter
    "BUEY",
    "FOCA",
    "GATO",
    "LEON",
    "LOBO",
    "MONO",
    "PATO",
    "PUMA",
    "RANA",
    "RATA",
    "TORO",
    "VACA",
    // 5-letter
    "BURRO",
    "CABRA",
    "CEBRA",
    "CERDO",
    "KOALA",
    "LINCE",
    "LLAMA",
    "MORSA",
    "OVEJA",
    "PERRO",
    "TIGRE",
    "ZORRO",
    // 6-letter
    "CASTOR",
    "CIERVO",
    "CONEJO",
    "DELFIN",
    "GORILA",
    "IGUANA",
    "JAGUAR",
    "JIRAFA",
    "LIEBRE",
    "NUTRIA",
    "PAJARO",
    // 7-letter
    "ARDILLA",
    "BALLENA",
    "BISONTE",
    "CABALLO",
    "CAMELLO",
    "CANGURO",
    "HAMSTER",
    "PANTERA",
    "TORTUGA",
    // 8-letter
    "CAMALEON",
    "ELEFANTE",
    "LEOPARDO",
    "MARIPOSA",
    // 9-letter
    "COCODRILO",
    "ORANGUTAN",
    "SERPIENTE",
  ],
  food: [
    // 3-letter
    "PAN",
    "SAL",
    "TAN",
    "UVA",
    // 4-letter
    "FLAN",
    "MAIZ",
    "MIEL",
    "PAPA",
    "PERA",
    "SOPA",
    "TACO",
    // 5-letter
    "ARROZ",
    "CARNE",
    "CREMA",
    "FRESA",
    "HUEVO",
    "JAMON",
    "LECHE",
    "LIMON",
    "MANGO",
    "PASTA",
    "PIZZA",
    "POLLO",
    "QUESO",
    "SALSA",
    "TORTA",
    // 6-letter
    "ACEITE",
    "CEREAL",
    "HELADO",
    "PASTEL",
    "SALMON",
    "TOCINO",
    "YOGURT",
    // 7-letter
    "CEBOLLA",
    "CHORIZO",
    "GALLETA",
    "NARANJA",
    "PESCADO",
    "PLATANO",
    "VERDURA",
    // 8-letter
    "AGUACATE",
    "CALABAZA",
    "CANGREJO",
    "ENSALADA",
    "ESPINACA",
    "LANGOSTA",
    "SANDWICH",
    // 9-letter
    "ALBONDIGA",
    "CAMARONES",
    "CHOCOLATE",
    "CROISSANT",
    "ESPAGUETI",
    "ZANAHORIA",
  ],
  fruits: [
    // 3-letter
    "UVA",
    // 4-letter
    "COCO",
    "HIGO",
    "KIWI",
    "LIMA",
    "MORA",
    "PERA",
    // 5-letter
    "DATIL",
    "FRESA",
    "GUAVA",
    "LIMON",
    "MANGO",
    "MELON",
    // 6-letter
    "BANANA",
    "CEREZA",
    "PAPAYA",
    "SANDIA",
    // 7-letter
    "CIRUELA",
    "DURAZNO",
    "GRANADA",
    "GUAYABA",
    "MANZANA",
    "NARANJA",
    "PLATANO",
    "TORONJA",
    // 8-letter
    "AGUACATE",
    "ARANDANO",
    "MARACUYA",
    // 9-letter
    "CARAMBOLA",
    "CHIRIMOYA",
    "FRAMBUESA",
    "MANDARINA",
    "NECTARINA",
    "TAMARINDO",
  ],
  colors: [
    // 3-letter
    "ORO",
    "TAN",
    // 4-letter
    "AZUL",
    "GRIS",
    "JADE",
    "ROJO",
    "ROSA",
    "VINO",
    // 5-letter
    "ARENA",
    "BEIGE",
    "CORAL",
    "CREMA",
    "LIMON",
    "NEGRO",
    "NIEVE",
    "OLIVA",
    "PLATA",
    "VERDE",
    // 6-letter
    "BLANCO",
    "BRONCE",
    "CENIZA",
    "DORADO",
    "FUCSIA",
    "INDIGO",
    "MARFIL",
    "MARRON",
    "MORADO",
    "SALMON",
    // 7-letter
    "BORGONA",
    "BURDEOS",
    "CARMESI",
    "CELESTE",
    "GRANATE",
    "LAVANDA",
    "MAGENTA",
    "NARANJA",
    "PURPURA",
    "VIOLETA",
    // 8-letter
    "AMARILLO",
    "PLATEADO",
    "TURQUESA",
    // 9-letter
    "CHOCOLATE",
    "ESCARLATA",
    "ESMERALDA",
    "TERRACOTA",
  ],
  body: [
    // 3-letter
    "OJO",
    "PIE",
    "UNA",
    // 4-letter
    "BOCA",
    "CARA",
    "CODO",
    "DEDO",
    "MANO",
    "OIDO",
    "PELO",
    "PIEL",
    "VENA",
    // 5-letter
    "BRAZO",
    "HUESO",
    "LABIO",
    "MUSLO",
    "NARIZ",
    "PECHO",
    "RINON",
    "TALON",
    "TORSO",
    // 6-letter
    "CABEZA",
    "CADERA",
    "CUELLO",
    "CUERPO",
    "DIENTE",
    "ESPINA",
    "FRENTE",
    "HIGADO",
    "HOMBRO",
    "LENGUA",
    "MUNECA",
    "PULGAR",
    "PULMON",
    "SANGRE",
    "TENDON",
    // 7-letter
    "CEREBRO",
    "COLUMNA",
    "CORAZON",
    "ESPALDA",
    "MUSCULO",
    "PESTANA",
    "RODILLA",
    "TOBILLO",
    // 8-letter
    "COSTILLA",
    "ESTOMAGO",
    "GARGANTA",
    "PANCREAS",
    "VERTEBRA",
    // 9-letter
    "CLAVICULA",
    "DIAFRAGMA",
    "INTESTINO",
    "MANDIBULA",
  ],
  family: [
    // 3-letter
    "TIA",
    "TIO",
    // 4-letter
    "BEBE",
    "HIJO",
    "MAMA",
    "NINO",
    "PAPA",
    // 5-letter
    "MADRE",
    "MUJER",
    "NIETA",
    "NIETO",
    "NUERA",
    "PADRE",
    "PRIMA",
    "PRIMO",
    "YERNO",
    // 6-letter
    "ABUELA",
    "ABUELO",
    "CASADO",
    "CUNADO",
    "ESPOSA",
    "ESPOSO",
    "GEMELO",
    "MARIDO",
    "SUEGRA",
    "SUEGRO",
    // 7-letter
    "AHIJADO",
    "FAMILIA",
    "HERMANA",
    "HERMANO",
    "MADRINA",
    "PADRINO",
    "SOBRINO",
    // 8-letter
    "BISNIETO",
    "HEREDERO",
    "HIJASTRO",
    "PARIENTE",
    // 9-letter
    "BISABUELO",
    "MADRASTRA",
    "PADRASTRO",
  ],
  clothing: [
    // 3-letter
    "TOP",
    // 4-letter
    "BATA",
    "BOTA",
    "CAPA",
    "JEAN",
    "ROPA",
    // 5-letter
    "BLUSA",
    "BOTON",
    "FALDA",
    "GORRA",
    "GORRO",
    "MANGA",
    "TRAJE",
    // 6-letter
    "ABRIGO",
    "BIKINI",
    "CAMISA",
    "GUANTE",
    "JERSEY",
    "PIJAMA",
    "SUETER",
    "ZAPATO",
    // 7-letter
    "BERMUDA",
    "BUFANDA",
    "CALZADO",
    "CHALECO",
    "CHANDAL",
    "CORBATA",
    "PANUELO",
    "VESTIDO",
    // 8-letter
    "ALBORNOZ",
    "BOLSILLO",
    "CALCETIN",
    "CAMISETA",
    "CAZADORA",
    "CHAQUETA",
    "CINTURON",
    "CONJUNTO",
    "LENCERIA",
    "LEOTARDO",
    "PANTALON",
    "PANTUFLA",
    "SANDALIA",
    "SOMBRERO",
    "SUDADERA",
    "TIRANTES",
    "UNIFORME",
    // 9-letter
    "GABARDINA",
    "ZAPATILLA",
  ],
  kitchen: [
    // 3-letter
    "OLA",
    "SAL",
    // 4-letter
    "COPA",
    "MESA",
    "OLLA",
    "TAZA",
    "VASO",
    // 5-letter
    "GRIFO",
    "HORNO",
    "PLATO",
    "TABLA",
    // 6-letter
    "COCINA",
    "ESTUFA",
    "NEVERA",
    "SARTEN",
    // 7-letter
    "BANDEJA",
    "BOTELLA",
    "CAMPANA",
    "COLADOR",
    "CUCHARA",
    "HIELERA",
    "TENEDOR",
    // 8-letter
    "BATIDORA",
    "CACEROLA",
    "CAFETERA",
    "CUBIERTO",
    "CUCHILLO",
    "DELANTAL",
    "PAELLERA",
    "RALLADOR",
    "TOSTADOR",
    // 9-letter
    "ABRELATAS",
    "CUCHARADA",
    "CUCHARITA",
    "FREGADERO",
    "LICUADORA",
    "MEZCLADOR",
    "RECETARIO",
    "TOSTADORA",
  ],
  school: [
    // 3-letter
    "GIS",
    "LUZ",
    // 4-letter
    "AULA",
    "BECA",
    "GOMA",
    "MAPA",
    "MESA",
    "NOTA",
    "TEST",
    // 5-letter
    "CLASE",
    "CURSO",
    "GRADO",
    "GRITO",
    "LAPIZ",
    "LIBRO",
    "PAPEL",
    "PATIO",
    "PLUMA",
    "REGLA",
    "TAREA",
    "TUTOR",
    // 6-letter
    "ALUMNO",
    "CAMPUS",
    "CARTEL",
    "COMPAS",
    "DIBUJO",
    "EXAMEN",
    "MUSICA",
    "RECREO",
    // 7-letter
    "APUNTES",
    "CALCULO",
    "CARPETA",
    "CIENCIA",
    "COLEGIO",
    "DEBERES",
    "DIPLOMA",
    "ESCOLAR",
    "ESCUELA",
    "ESTUCHE",
    "ESTUDIO",
    "LECCION",
    "LECTURA",
    "MAESTRO",
    "MATERIA",
    "PINTURA",
    "PIZARRA",
    "PUPITRE",
    "QUIMICA",
    "RESUMEN",
    // 8-letter
    "BIOLOGIA",
    "BORRADOR",
    "CUADERNO",
    "DIRECTOR",
    "GIMNASIO",
    "HISTORIA",
    // 9-letter
    "CAFETERIA",
    "EDUCACION",
    "ESCRITURA",
    "GEOMETRIA",
    "PROFESORA",
  ],
  garden: [
    // 3-letter
    "SOL",
    "VID",
    // 4-letter
    "FLOR",
    "HOJA",
    "PALA",
    "RAIZ",
    "RAMA",
    "ROSA",
    // 5-letter
    "ABONO",
    "ARBOL",
    "BROTE",
    "BULBO",
    "DALIA",
    "FRUTA",
    "HONGO",
    "LIRIO",
    "MUSGO",
    "PASTO",
    "RIEGO",
    "TALLO",
    // 6-letter
    "AZALEA",
    "CESPED",
    "CLAVEL",
    "HIERBA",
    "HUERTO",
    "JARDIN",
    "JAZMIN",
    "MACETA",
    "PLANTA",
    "TIERRA",
    // 7-letter
    "ARBUSTO",
    "BEGONIA",
    "CAMELIA",
    "CAMPANA",
    "COMPOST",
    "GERANIO",
    "GIRASOL",
    "JACINTO",
    "LAVANDA",
    "PETUNIA",
    "SEMBRAR",
    "SEMILLA",
    "TULIPAN",
    // 8-letter
    "ABEJORRO",
    "CLAVELES",
    "CULTIVAR",
    "ESPATULA",
    "MANGUERA",
    "ORQUIDEA",
    "PODADORA",
    // 9-letter
    "FLORECIDO",
    "GARDENIAS",
    "GIRASOLES",
    "HERBICIDA",
    "HORTENSIA",
    "JARDINERO",
    "MARGARITA",
    "POLINIZAR",
    "PRIMAVERA",
  ],
  birds: [
    // 3-letter
    "AVE",
    // 4-letter
    "BUHO",
    "LORO",
    "PATO",
    "PAVO",
    // 5-letter
    "CISNE",
    "GALLO",
    "GANSO",
    "MIRLO",
    "TORDO",
    "TUCAN",
    // 6-letter
    "AGUILA",
    "CONDOR",
    "CUERVO",
    "GAVINA",
    "GRULLA",
    "HALCON",
    "MARTIN",
    "PALOMA",
    "PERDIZ",
    "PERICO",
    "URRACA",
    // 7-letter
    "CACATUA",
    "CANARIO",
    "COLIBRI",
    "GAVIOTA",
    "LECHUZA",
    // 8-letter
    "ALBATROS",
    "AVESTRUZ",
    "CARDENAL",
    "CODORNIZ",
    "FLAMENCO",
    "JILGUERO",
    "PAPAGAYO",
    "PELICANO",
    "PICAFLOR",
    // 9-letter
    "PERIQUITO",
  ],
  insects: [
    // 4-letter
    "PUPA",
    // 5-letter
    "ABEJA",
    "ACARO",
    "AFIDO",
    "ARANA",
    "LARVA",
    "MOSCA",
    "NINFA",
    "ORUGA",
    "PIOJO",
    "PULGA",
    // 6-letter
    "AVISPA",
    "GRILLO",
    "MANTIS",
    "PULGON",
    "TABANO",
    // 7-letter
    "AVISPON",
    "CHINCHE",
    "CIGARRA",
    "GORGOJO",
    "HORMIGA",
    "MILPIES",
    "POLILLA",
    "TERMITA",
    "ZANCUDO",
    // 8-letter
    "ABEJORRO",
    "CIEMPIES",
    "LANGOSTA",
    "LIBELULA",
    "MARIPOSA",
    "MOSQUITO",
    "TIJERETA",
    // 9-letter
    "CUCARACHA",
    "ESCORPION",
    "GARRAPATA",
    "MARIQUITA",
  ],
  weather: [
    // 3-letter
    "LUZ",
    "SOL",
    // 4-letter
    "AGUA",
    "AIRE",
    "FRIO",
    "HALO",
    "NUBE",
    "OLAS",
    "RAYO",
    // 5-letter
    "BRISA",
    "BRUMA",
    "CALOR",
    "CIELO",
    "CLIMA",
    "HIELO",
    "NIEVE",
    "POLAR",
    "TIFON",
    "VAPOR",
    // 6-letter
    "CICLON",
    "FRESCO",
    "HELADA",
    "MONZON",
    "NEVADA",
    "NIEBLA",
    "NUBOSO",
    "SEQUIA",
    "SERENO",
    "TRUENO",
    "VIENTO",
    // 7-letter
    "CELSIUS",
    "DILUVIO",
    "GALERNA",
    "GRANIZO",
    "HELADAS",
    "HUMEDAD",
    "HURACAN",
    "NEBLINA",
    "NEVASCA",
    "NUBLADO",
    "SOLEADO",
    "TORNADO",
    // 8-letter
    "AGUACERO",
    "AMBIENTE",
    "ARCOIRIS",
    "BOCHORNO",
    "CHUBASCO",
    "ESCARCHA",
    "LLOVIZNA",
    "TEMPESTA",
    "TORMENTA",
    // 9-letter
    "ATMOSFERA",
    "BAROMETRO",
    "BORRASCAS",
    "CENTELLAS",
    "DESPEJADO",
    "GRANIZADA",
    "RELAMPAGO",
    "TEMPESTAD",
    "TERREMOTO",
  ],
  ocean: [
    // 3-letter
    "MAR",
    "OLA",
    "PEZ",
    // 4-letter
    "ALGA",
    "ATUN",
    "BOTE",
    "BOYA",
    "CABO",
    "FARO",
    "REMO",
    "ROCA",
    "VELA",
    "YATE",
    // 5-letter
    "ANCLA",
    "BAHIA",
    "BARCO",
    "BUQUE",
    "CORAL",
    "COSTA",
    "FAROL",
    "FONDO",
    "GOLFO",
    "MAREA",
    "MARIN",
    "NAVIO",
    "OSTRA",
    "PERLA",
    "PESCA",
    "PLAYA",
    "PULPO",
    // 6-letter
    "ALMEJA",
    "BUCEAR",
    "DELFIN",
    "GOLETA",
    "MARINO",
    "MEDUSA",
    "MUELLE",
    "OCEANO",
    "PUERTO",
    "SIRENA",
    "VELERO",
    // 7-letter
    "ACUARIO",
    "AGUAMAN",
    "BALLENA",
    "CRUCERO",
    "ESPONJA",
    "ICEBERG",
    "LITORAL",
    "MANGLAR",
    "MEDUSAS",
    "NAUTICO",
    "TIBURON",
    // 8-letter
    "ARRECIFE",
    "BALLENAS",
    "CANGREJO",
    "CARABELA",
    "CARACOLA",
    "ESTRELLA",
    "LANGOSTA",
    "MACARELA",
    "MARINERO",
    "MARISCOS",
    "PESCADOR",
    "PROFUNDO",
    "SURFISTA",
    // 9-letter
    "CABALLITO",
    "CAMARONES",
    "CRUSTACEO",
    "HIPOCAMPO",
    "NAUFRAGIO",
    "NAVEGANTE",
    "SUBMARINO",
  ],
  sports: [
    // 3-letter
    "GOL",
    "RED",
    "SKI",
    // 4-letter
    "ARCO",
    "BATE",
    "BICI",
    "BOLA",
    "CLUB",
    "GOLF",
    "JUDO",
    "META",
    "PASE",
    "POLO",
    "RING",
    "TIRO",
    // 5-letter
    "ARBIT",
    "BOXEO",
    "ESQUI",
    "FINAL",
    "GOLES",
    "LUCHA",
    "NADAR",
    "PISTA",
    "RUGBY",
    "SALTO",
    "TENIS",
    // 6-letter
    "ATLETA",
    "CANCHA",
    "CORRER",
    "EQUIPO",
    "FUTBOL",
    "HOCKEY",
    "KARATE",
    "TORNEO",
    "TROFEO",
    // 7-letter
    "ARQUERO",
    "BEISBOL",
    "CARRERA",
    "DEFENSA",
    "ESQUIAR",
    "ESTADIO",
    "JUGADOR",
    "MARATON",
    "MEDALLA",
    "PATINAR",
    "PISCINA",
    "PORTERO",
    "RAQUETA",
    "REFEREE",
    // 8-letter
    "CICLISMO",
    "CICLISTA",
    "DECATLON",
    "ESCALADA",
    "GIMNASIA",
    "GIMNASIO",
    "NATACION",
    "PELOTARI",
    "SURFISTA",
    "VICTORIA",
    "VOLEIBOL",
    // 9-letter
    "ALPINISMO",
    "ATLETISMO",
    "BADMINTON",
    "BALONMANO",
    "DELANTERO",
    "SEMIFINAL",
    "TRIATHLON",
  ],
  music: [
    // 3-letter
    "POP",
    "RAP",
    "VOZ",
    // 4-letter
    "ARPA",
    "BAJO",
    "CORO",
    "GONG",
    "JAZZ",
    "NOTA",
    "OBOE",
    "ONDA",
    "ROCK",
    "SOLO",
    "TRIO",
    "TUBA",
    // 5-letter
    "AUDIO",
    "BAILE",
    "BANDA",
    "BLUES",
    "CANTO",
    "CELLO",
    "CLAVE",
    "CONGA",
    "DISCO",
    "DUETO",
    "GRUPO",
    "HIMNO",
    "MAMBO",
    "OPERA",
    "PIANO",
    "POLCA",
    "RADIO",
    "RITMO",
    "RUMBA",
    "SALSA",
    "TENOR",
    "TROVA",
    "VALSE",
    // 6-letter
    "ACORDE",
    "BALADA",
    "BOLERO",
    "CUMBIA",
    "ENSAYO",
    "FAGOTE",
    "FLAUTA",
    "MUSICO",
    "REGGAE",
    "SONIDO",
    "TAMBOR",
    "TIMBAL",
    "VIOLIN",
    // 7-letter
    "ARMONIA",
    "BATERIA",
    "GUITARR",
    "MELODIA",
    "SAXOFON",
    "SOLISTA",
    "TECLADO",
    // 8-letter
    "ACORDEON",
    "ARMONICA",
    "CANTANTE",
    "DIRECTOR",
    "GUITARRA",
    "MARIACHI",
    "ORQUESTA",
    "PIANISTA",
    "SINFONIA",
    "TROMPETA",
    "XILOFONO",
    // 9-letter
    "BANDURRIA",
    "CLARINETE",
    "CONCIERTO",
    "DISCOTECA",
    "PERCUSION",
  ],
  travel: [
    // 3-letter
    "BUS",
    "IDA",
    "MAR",
    "VIA",
    // 4-letter
    "AUTO",
    "BICI",
    "FARO",
    "GUIA",
    "MAPA",
    "META",
    "MOTO",
    "NAVE",
    "RUTA",
    "TAXI",
    "TREN",
    "VELO",
    "VISA",
    // 5-letter
    "AVION",
    "BARCO",
    "COSTA",
    "CRUCE",
    "FERRY",
    "HOTEL",
    "METRO",
    "PASEO",
    "PLAYA",
    "VIAJE",
    "VUELO",
    // 6-letter
    "ADUANA",
    "BOLETO",
    "CAMINO",
    "MALETA",
    "MUELLE",
    "PASAJE",
    "POSTAL",
    "PUERTO",
    // 7-letter
    "ASIENTO",
    "AUTOBUS",
    "BILLETE",
    "BRUJULA",
    "CRUCERO",
    "DESTINO",
    "LLEGADA",
    "MIRADOR",
    "PAISAJE",
    "PARTIDA",
    "REGRESO",
    "RESERVA",
    "TURISMO",
    "TURISTA",
    "VIAJERO",
    // 8-letter
    "AVENTURA",
    "CONEXION",
    "EQUIPAJE",
    "ESCALADA",
    "ESTACION",
    "FRONTERA",
    "PASAJERO",
    "TERMINAL",
    "TRAVESIA",
    "VACACION",
    // 9-letter
    "AEROLINEA",
    "CAMIONETA",
    "CARRETERA",
    "EXCURSION",
    "HORIZONTE",
    "HOSPEDAJE",
    "MONUMENTO",
    "PASAJEROS",
    "PASAPORTE",
    "RECORRIDO",
  ],
  space: [
    // 3-letter
    "LUZ",
    "SOL",
    // 4-letter
    "LUNA",
    "NASA",
    "NAVE",
    "OVNI",
    // 5-letter
    "ALIEN",
    "APOLO",
    "ASTRO",
    "CIELO",
    "FLOTE",
    "LUNAR",
    "MARTE",
    "PLUTO",
    "RADAR",
    "SONDA",
    "URANO",
    "VENUS",
    // 6-letter
    "COHETE",
    "COMETA",
    "COSMOS",
    "CRATER",
    "MISION",
    "NEBULA",
    "ORBITA",
    "PLUTON",
    // 7-letter
    "ECLIPSE",
    "ESPACIO",
    "GALAXIA",
    "METEORO",
    "NEPTUNO",
    "ORBITAL",
    "PLANETA",
    "SATURNO",
    "SISTEMA",
    // 8-letter
    "ESTACION",
    "ESTRELLA",
    "GALAXIAS",
    "GRAVEDAD",
    "MERCURIO",
    "SATELITE",
    "UNIVERSO",
    // 9-letter
    "ASTEROIDE",
    "ATMOSFERA",
    "ESTRELLAS",
    "METEORITO",
  ],
  tools: [
    // 3-letter
    "LUZ",
    // 4-letter
    "CAVO",
    "GATO",
    "LIMA",
    "PALA",
    "PICO",
    "SOGA",
    "TUBO",
    // 5-letter
    "BROCA",
    "CABLE",
    "CLAVO",
    "HACHA",
    "LLAVE",
    "MANGO",
    "METRO",
    "NIVEL",
    "PERNO",
    "PINZA",
    "PUNTA",
    // 6-letter
    "CADENA",
    "CINCEL",
    "TENAZA",
    "TUERCA",
    // 7-letter
    "ALAMBRE",
    "ALICATE",
    "ANDAMIO",
    "CEPILLO",
    "CIZALLA",
    "ENGRASE",
    "ESCOPLO",
    "MACHETE",
    "PALANCA",
    "TALADRO",
    "TENAZAS",
    // 8-letter
    "AFILADOR",
    "CALADIZO",
    "ESCALERA",
    "LIJADORA",
    "LINTERNA",
    "MARTILLO",
    "SERRUCHO",
    "SOLDADOR",
    "TORNILLO",
    // 9-letter
    "AMOLADORA",
    "COMPRESOR",
    "CORTADORA",
    "SOLDADORA",
    "SOLDADURA",
  ],
  countries: [
    // 3-letter
    "USA",
    // 4-letter
    "CHAD",
    "CUBA",
    "FIJI",
    "IRAK",
    "IRAN",
    "LAOS",
    "MALI",
    "OMAN",
    "PERU",
    "TOGO",
    // 5-letter
    "BENIN",
    "BUTAN",
    "CHILE",
    "CHINA",
    "GABON",
    "GHANA",
    "HAITI",
    "INDIA",
    "JAPON",
    "KENIA",
    "LIBIA",
    "MALTA",
    "NEPAL",
    "NIGER",
    "QATAR",
    "RUSIA",
    "SIRIA",
    "TONGA",
    "TUNEZ",
    "YEMEN",
    // 6-letter
    "BELICE",
    "BRASIL",
    "BRUNEI",
    "CANADA",
    "CHIPRE",
    "EGIPTO",
    "GRECIA",
    "GUYANA",
    "ISRAEL",
    "ITALIA",
    "KUWAIT",
    "LIBANO",
    "MALAWI",
    "MEXICO",
    "MONACO",
    "PANAMA",
    "SERBIA",
    "SUECIA",
    "TUVALU",
    "UGANDA",
    "YIBUTI",
    "ZAMBIA",
    // 7-letter
    "ALBANIA",
    "ANDORRA",
    "ARGELIA",
    "ARMENIA",
    "AUSTRIA",
    "BAHAMAS",
    "BAHREIN",
    "BELGICA",
    "BOLIVIA",
    "CAMBOYA",
    "CAMERUN",
    "CROACIA",
    "ECUADOR",
    "ERITREA",
    "ESTONIA",
    "ETIOPIA",
    "FRANCIA",
    "GEORGIA",
    "GRANADA",
    "HUNGRIA",
    "IRLANDA",
    "JAMAICA",
    "LETONIA",
    "LIBERIA",
    "MALASIA",
    "MYANMAR",
    "NAMIBIA",
    "NIGERIA",
    "NORUEGA",
    "POLONIA",
    "RUMANIA",
    "SENEGAL",
    "SURINAM",
    "UCRANIA",
    "URUGUAY",
    "VANUATU",
    "VIETNAM",
    // 8-letter
    "ALEMANIA",
    "BARBADOS",
    "BOTSUANA",
    "BULGARIA",
    "COLOMBIA",
    "DOMINICA",
    "HONDURAS",
    "ISLANDIA",
    "JORDANIA",
    "KIRIBATI",
    "LITUANIA",
    "MALDIVAS",
    "MAURICIO",
    "MOLDAVIA",
    "MONGOLIA",
    "PAKISTAN",
    "PARAGUAY",
    "PORTUGAL",
    "SINGAPUR",
    "SRILANKA",
    "TANZANIA",
    "ZIMBABUE",
    // 9-letter
    "ARGENTINA",
    "AUSTRALIA",
    "DINAMARCA",
    "ESLOVENIA",
    "FINLANDIA",
    "GUATEMALA",
    "INDONESIA",
    "MARRUECOS",
    "NICARAGUA",
    "TAILANDIA",
    "VENEZUELA",
  ],
  vehicles: [
    // 3-letter
    "BUS",
    // 4-letter
    "AUTO",
    "BICI",
    "BOTE",
    "GRUA",
    "JEEP",
    "MOTO",
    "NAVE",
    "TAXI",
    "TREN",
    "YATE",
    // 5-letter
    "AVION",
    "BARCO",
    "BUGGY",
    "CANOA",
    "CARRO",
    "FERRY",
    "GLOBO",
    "KAYAK",
    "METRO",
    "MOPED",
    "SEDAN",
    "VAGON",
    // 6-letter
    "CAMION",
    "COHETE",
    "FURGON",
    "LANCHA",
    "TANQUE",
    "TRINEO",
    "VELERO",
    // 7-letter
    "AUTOBUS",
    "BIPLANO",
    "CARRETA",
    "CARROZA",
    "CRUCERO",
    "GONDOLA",
    "OMNIBUS",
    "TRACTOR",
    "TRAILER",
    "TRANVIA",
    // 8-letter
    "AERONAVE",
    "BICIMOTO",
    "CARRETON",
    "LIMUSINA",
    "PATINETA",
    "REMOLQUE",
    "TRICICLO",
    "VOLQUETE",
    // 9-letter
    "AEROPLANO",
    "AUTOMOVIL",
    "BICICLETA",
    "CAMIONETA",
    "FURGONETA",
    "MONORRIEL",
    "SUBMARINO",
  ],
  flowers: [
    // 3-letter
    "LIS",
    // 4-letter
    "IRIS",
    "LILA",
    "ROSA",
    // 5-letter
    "ASTER",
    "CALLA",
    "DALIA",
    "LIRIO",
    "MALVA",
    "VIOLA",
    // 6-letter
    "ADELFA",
    "AZALEA",
    "CLAVEL",
    "CROCUS",
    "FRESIA",
    "FUCSIA",
    "JAZMIN",
    "PEONIA",
    "SALVIA",
    "ZINNIA",
    // 7-letter
    "AMAPOLA",
    "ANEMONA",
    "AZUCENA",
    "BEGONIA",
    "CAMELIA",
    "CAMPANA",
    "ESPUELA",
    "GERANIO",
    "GIRASOL",
    "HIBISCO",
    "JACINTO",
    "LAVANDA",
    "NARCISO",
    "PETUNIA",
    "PRIMULA",
    "TULIPAN",
    "VERBENA",
    "VIOLETA",
    // 8-letter
    "AMARILIS",
    "GARDENIA",
    "GLADIOLO",
    "GLOXINIA",
    "MAGNOLIA",
    // 9-letter
    "CALENDULA",
    "CAPUCHINA",
    "CLAVELINA",
    "HORTENSIA",
    "JONQUILLO",
    "MARGARITA",
    "MILENRAMA",
  ],
  desserts: [
    // 3-letter
    "PAN",
    // 4-letter
    "BOLO",
    "FLAN",
    // 5-letter
    "BOLLO",
    "BRAZO",
    "BUDIN",
    "CREMA",
    "CREPA",
    "DULCE",
    "FRUTA",
    "TARTA",
    "TORTA",
    "TRUFA",
    // 6-letter
    "BATIDO",
    "BOMBON",
    "CANOLI",
    "CHURRO",
    "GATEAU",
    "HELADO",
    "MANJAR",
    "MOUSSE",
    "MUFFIN",
    "PANQUE",
    "PASTEL",
    "WAFFLE",
    // 7-letter
    "ALFAJOR",
    "BAKLAVA",
    "BERLINA",
    "BROWNIE",
    "CARLOTA",
    "COBBLER",
    "COMPOTA",
    "CRUMBLE",
    "CUPCAKE",
    "ECLAIRE",
    "FONDANT",
    "GALLETA",
    "GRANITA",
    "MILHOJA",
    "NATILLA",
    "PALMERA",
    "SORBETE",
    // 8-letter
    "ALMENDRA",
    "BAVAROIS",
    "BIZCOCHO",
    "CARAMELO",
    "CUBANITO",
    "EMPANADA",
    "GELATINA",
    "HOJALDRE",
    "MARQUESA",
    "MERENGUE",
    // 9-letter
    "BARQUILLO",
    "CHANTILLY",
    "CHOCOLATE",
    "CRUJIENTE",
    "MAGDALENA",
    "PANETTONE",
  ],
  jobs: [
    // 3-letter
    "REY",
    // 4-letter
    "CHEF",
    "CURA",
    "GUIA",
    "JUEZ",
    "MOZO",
    // 5-letter
    "ACTOR",
    "AUTOR",
    "MONJE",
    "TUTOR",
    // 6-letter
    "ATLETA",
    "CAJERA",
    "CAJERO",
    "CHOFER",
    "DOCTOR",
    "EDITOR",
    "JOYERO",
    "MESERO",
    "MINERO",
    "MUSICO",
    "OBRERO",
    "PILOTO",
    "PINTOR",
    "SASTRE",
    // 7-letter
    "ABOGADA",
    "ABOGADO",
    "ARTISTA",
    "BARBERO",
    "BOMBERA",
    "BOMBERO",
    "CARTERO",
    "GERENTE",
    "HERRERO",
    "LOCUTOR",
    "MAESTRO",
    "PLOMERO",
    "PORTERO",
    "SOLDADO",
    // 8-letter
    "ANALISTA",
    "CAMARERO",
    "CANTANTE",
    "COCINERO",
    "CONTADOR",
    "DENTISTA",
    "ESCRITOR",
    "ESCULTOR",
    "FLORISTA",
    "GRANJERO",
    "MARINERO",
    "PANADERO",
    "PEDIATRA",
    "PESCADOR",
    "PROFESOR",
    "VENDEDOR",
    "ZAPATERO",
    // 9-letter
    "CERRAJERO",
    "COMADRONA",
    "CONDUCTOR",
    "CONSEJERO",
    "CONTADORA",
    "DETECTIVE",
    "ENFERMERA",
    "ENFERMERO",
    "INGENIERO",
    "INSPECTOR",
    "JARDINERO",
    "MAYORDOMO",
    "PELUQUERO",
    "TRADUCTOR",
  ],
  furniture: [
    // 3-letter
    "LUZ",
    // 4-letter
    "BURO",
    "CAMA",
    "MESA",
    "SOFA",
    // 5-letter
    "BANCO",
    "CESTA",
    "COFRE",
    "FUTON",
    "JAULA",
    "SILLA",
    // 6-letter
    "BIOMBO",
    "BUTACA",
    "CANAPE",
    "CLOSET",
    "COMODA",
    "ESPEJO",
    "HAMACA",
    "LITERA",
    "MESITA",
    "MUEBLE",
    "REPISA",
    "ROPERO",
    "SILLON",
    "TAPETE",
    // 7-letter
    "ALACENA",
    "ANAQUEL",
    "ARMARIO",
    "CONSOLA",
    "ESCABEL",
    "ESTANTE",
    "LIBRERO",
    "OTOMANA",
    "TOCADOR",
    "VITRINA",
    // 8-letter
    "ALFOMBRA",
    "APARADOR",
    "CABECERA",
    "CABECERO",
    "CAJONERA",
    "CREDENZA",
    "GABINETE",
    "MECEDORA",
    "PERCHERO",
    "POLTRONA",
    "RECAMARA",
    "SECRETER",
    "TABURETE",
    "ZAPATERO",
    // 9-letter
    "ANAQUELES",
    "ARCHIVERO",
    "BUTAQUITA",
    "MOSTRADOR",
  ],
  drinks: [
    // 3-letter
    "RON",
    // 4-letter
    "AGUA",
    "CAVA",
    "COLA",
    "JUGO",
    "MATE",
    "MIEL",
    "VINO",
    // 5-letter
    "ATOLE",
    "CACAO",
    "CIDRA",
    "COCOA",
    "JEREZ",
    "LECHE",
    "LICOR",
    "LIMON",
    "MALTA",
    "MOSTO",
    "PISCO",
    "SIDRA",
    "TINTO",
    // 6-letter
    "BATIDO",
    "BRANDY",
    "CEBADA",
    "CHICHA",
    "FRAPPE",
    "MOJITO",
    "PONCHE",
    "PULQUE",
    "VERMUT",
    "WHISKY",
    "YOGURT",
    // 7-letter
    "ABSENTA",
    "CERVEZA",
    "GINEBRA",
    "GUARAPO",
    "LICORES",
    "LICUADO",
    "MARTINI",
    "ROMPOPE",
    "TEQUILA",
    // 8-letter
    "AMARETTO",
    "BURBUJAS",
    "CHINOTTO",
    "ESPRESSO",
    "HORCHATA",
    "LIMONADA",
    "MALTEADA",
    "REFRESCO",
    "SMOOTHIE",
    // 9-letter
    "CAPUCHINO",
    "CERVECITA",
    "CHAMPAGNE",
    "CHOCOLATE",
    "GRANADINA",
    "GRANIZADO",
    "LICUADORA",
    "MARGARITA",
    "MERENGADA",
    "MICHELADA",
    "NARANJADA",
  ],
  gems: [
    // 3-letter
    "ORO",
    // 4-letter
    "GEMA",
    "JADE",
    "JOYA",
    "ONIX",
    "RUBI",
    // 5-letter
    "AGATA",
    "AMBAR",
    "CORAL",
    "JASPE",
    "NACAR",
    "OPALO",
    "PERLA",
    // 6-letter
    "BERILO",
    "CUARZO",
    "MARFIL",
    "PIEDRA",
    "PIROPO",
    "ZAFIRO",
    // 7-letter
    "APATITA",
    "CITRINA",
    "CRISTAL",
    "GRANATE",
    "MINERAL",
    "OLIVINO",
    "PIEDRAS",
    "TOPACIO",
    // 8-letter
    "AMATISTA",
    "DIAMANTE",
    "ESPINELA",
    "FLUORITA",
    "HEMATITA",
    "PERIDOTO",
    "RODONITA",
    "TURQUESA",
    // 9-letter
    "AMAZONITA",
    "BRILLANTE",
    "CELESTINA",
    "CORNALINA",
    "CRISOPRAS",
    "ESMERALDA",
    "MALAQUITA",
    "MARCASITA",
    "OBSIDIANA",
    "TANZANITA",
    "TURMALINA",
  ],
  dance: [
    // 3-letter
    "HIP",
    "POP",
    // 4-letter
    "BOLA",
    "GALA",
    "HULA",
    "JAZZ",
    "JIVE",
    "PASO",
    "PROM",
    "REEL",
    "VALS",
    // 5-letter
    "BAILE",
    "BOMBA",
    "CONGA",
    "DANZA",
    "DISCO",
    "MAMBO",
    "PLENA",
    "POLCA",
    "POLKA",
    "RITMO",
    "RUMBA",
    "SALSA",
    "SAMBA",
    "SWING",
    "TANGO",
    "TWIST",
    // 6-letter
    "BALLET",
    "BOLERO",
    "CANCAN",
    "CHOTIS",
    "CUMBIA",
    "FIESTA",
    "JARABE",
    "PAVANA",
    // 7-letter
    "BACHATA",
    "CABARET",
    "FESTEJO",
    "FOXTROT",
    "MAZURCA",
    "MILONGA",
    "MINUETO",
    "PASILLO",
    "PIRUETA",
    "VERBENA",
    "ZAPATEO",
    // 8-letter
    "ARABESCO",
    "CAPOEIRA",
    "CARNAVAL",
    "FANDANGO",
    "FLAMENCO",
    "GUARACHA",
    "HUAPANGO",
    "MACARENA",
    "MERENGUE",
    "PAMBICHE",
    "ZARANDEO",
    // 9-letter
    "BAILARINA",
    "DANZARINA",
    "DISCOTECA",
    "PASODOBLE",
    "QUICKSTEP",
    "SEVILLANA",
    "TARANTELA",
  ],
  trees: [
    // 3-letter
    "TIL",
    // 4-letter
    "ARCE",
    "COCO",
    "HAYA",
    "OLMO",
    "PINO",
    "TECA",
    "TEJO",
    "TILO",
    // 5-letter
    "ABETO",
    "ACEBO",
    "ALAMO",
    "ALISO",
    "ARBOL",
    "BAMBU",
    "CAOBA",
    "CEDRO",
    "CEIBO",
    "EBANO",
    "FICUS",
    "MANGO",
    "NOGAL",
    "OLIVO",
    "PALMA",
    "PERAL",
    "ROBLE",
    "SAUCE",
    // 6-letter
    "ABEDUL",
    "ACACIA",
    "BOSQUE",
    "CANELO",
    "CEREZO",
    "CIPRES",
    "ENCINA",
    "ENCINO",
    "FRESNO",
    "LAUREL",
    "MORERA",
    "PAPAYO",
    "POMELO",
    "SABINO",
    "SECOYA",
    "ZAPOTE",
    // 7-letter
    "CIRUELO",
    "DURAZNO",
    "GRANADO",
    "GUAYABO",
    "HIGUERA",
    "MANZANO",
    "NARANJO",
    "PALMERA",
    // 8-letter
    "ABEDULAR",
    "AGUACATE",
    "ALMENDRO",
    "ANACARDO",
    "ARBOLEDA",
    "AVELLANO",
    "COCOTERO",
    "FLORESTA",
    "FORESTAL",
    "LIMONERO",
    "MADERERA",
    "MAGNOLIO",
    "ROBLEDAL",
    // 9-letter
    "ALGARROBO",
    "ARAUCARIA",
    "AVELLANAS",
    "EUCALIPTO",
    "JACARANDA",
    "MANDARINO",
    "PALOSANTO",
    "PLATANERO",
    "TAMARINDO",
  ],
  reptiles: [
    // 3-letter
    "BOA",
    // 4-letter
    "RANA",
    "SAPO",
    // 5-letter
    "ANOLE",
    "COBRA",
    "GECKO",
    "MAMBA",
    "PITON",
    // 6-letter
    "CAIMAN",
    "DRAGON",
    "IGUANA",
    "REPTIL",
    "VIBORA",
    "YACARE",
    // 7-letter
    "ANGUILA",
    "CROTALO",
    "CULEBRA",
    "IGUANAS",
    "LAGARTO",
    "MONITOR",
    "PITONES",
    "TORTUGA",
    "TUATARA",
    // 8-letter
    "ALIGATOR",
    "ANACONDA",
    "CAMALEON",
    "CASCABEL",
    "CULEBRAS",
    "GAVIALES",
    "LAGARTOS",
    "TORTUGAS",
    // 9-letter
    "ANACONDAS",
    "BASILISCO",
    "COCODRILO",
    "LAGARTIJA",
    "LAGARTIJO",
    "SERPIENTE",
  ],
  seasons: [
    // 3-letter
    "DIA",
    "MAR",
    "SOL",
    // 4-letter
    "AIRE",
    "FLOR",
    "FRIO",
    "HOJA",
    "NIDO",
    "NUBE",
    "OLAS",
    "ROSA",
    // 5-letter
    "CALOR",
    "CLIMA",
    "FLORA",
    "HIELO",
    "HOJAS",
    "MARZO",
    "NIEVE",
    "OTONO",
    "PLAYA",
    "POLAR",
    "SELVA",
    "VERDE",
    "VITAL",
    // 6-letter
    "AGOSTO",
    "BROTES",
    "CAMBIO",
    "FRESCO",
    "HELADA",
    "HUMEDO",
    "LLUVIA",
    "NEVADA",
    "VERANO",
    // 7-letter
    "COSECHA",
    "ESTIVAL",
    "FEBRERO",
    "FLORIDA",
    "FRESCOS",
    "GLACIAL",
    "GRANIZO",
    "OCTUBRE",
    "SOLEADO",
    // 8-letter
    "AMBIENTE",
    "ARCOIRIS",
    "BOCHORNO",
    "CALIENTE",
    "ESTACION",
    "INVIERNO",
    "TEMPLADO",
    "TROPICAL",
    // 9-letter
    "DICIEMBRE",
    "FLORECIDO",
    "MIGRACION",
    "NOVIEMBRE",
    "PRIMAVERA",
    "SOLSTICIO",
    "TEMPORADA",
  ],
  cinema: [
    // 3-letter
    "SET",
    // 4-letter
    "CINE",
    "CLIP",
    "DIVA",
    "FAMA",
    "FILM",
    "GALA",
    "GUIA",
    "IDOL",
    "MUDO",
    "SALA",
    "STAR",
    "TOMA",
    // 5-letter
    "ACTOR",
    "AUDIO",
    "CORTO",
    "DRAMA",
    "EXTRA",
    "FINAL",
    "GUION",
    "IDOLO",
    "LARGO",
    "MACRO",
    "OSCAR",
    "PAUSA",
    "PLANO",
    "ROLLO",
    "VIDEO",
    // 6-letter
    "ACTRIZ",
    "BOBINA",
    "BUTACA",
    "CAMARA",
    "CARTEL",
    "ELENCO",
    "ESCENA",
    "GENERO",
    "RODAJE",
    // 7-letter
    "ANIMADO",
    "COMEDIA",
    "CREDITO",
    "DOBLAJE",
    "EDICION",
    "EFECTOS",
    "ESTRENO",
    "FICCION",
    "MONTAJE",
    "PUBLICO",
    "REPARTO",
    "SECUELA",
    "TRAILER",
    // 8-letter
    "ALFOMBRA",
    "AUDICION",
    "CINEASTA",
    "CINEFILO",
    "DIRECTOR",
    "ESTRELLA",
    "FANTASIA",
    "NOMINADO",
    "PALOMITA",
    "PANTALLA",
    "PELICULA",
    "PREMIERE",
    "SILENCIO",
    "TAQUILLA",
    // 9-letter
    "ACTUACION",
    "ANIMACION",
    "ARGUMENTO",
    "CINEASTAS",
    "FOTOGRAMA",
    "PERSONAJE",
    "PRODUCTOR",
    "SECUENCIA",
    "SUBTITULO",
  ],
  farm: [
    // 3-letter
    "AVE",
    "RES",
    "SOL",
    // 4-letter
    "AVES",
    "BALA",
    "BUEY",
    "CUBO",
    "HENO",
    "MAIZ",
    "MULA",
    "PAJA",
    "PATO",
    "RAZA",
    "SILO",
    "TORO",
    "VACA",
    // 5-letter
    "ABONO",
    "ARADO",
    "AVENA",
    "BURRO",
    "CABRA",
    "CAMPO",
    "CERCA",
    "CERDO",
    "GALLO",
    "GANSO",
    "GRANO",
    "HUEVO",
    "LECHE",
    "LLAMA",
    "OVEJA",
    "POLLO",
    "SUELO",
    "TRIGO",
    // 6-letter
    "ALPACA",
    "CEBADA",
    "CORRAL",
    "ESPIGA",
    "GANADO",
    "GRANJA",
    "HIERBA",
    "HUERTA",
    "MOLINO",
    "PASTOR",
    "RANCHO",
    // 7-letter
    "ALFALFA",
    "ALMACEN",
    "CABALLO",
    "COSECHA",
    "CULTIVO",
    "ESTABLO",
    "GALLINA",
    "GRANERO",
    "IRRIGAR",
    "PRADERA",
    "SEMBRAR",
    "SIEMBRA",
    "TRACTOR",
    // 8-letter
    "AGRICOLA",
    "CULTIVOS",
    "GANADERO",
    "GRANJERO",
    "LECHERIA",
    "PASTOREO",
    "PECUARIO",
    // 9-letter
    "ARRENDAJO",
    "CAMPESINO",
    "CAMPESTRE",
    "CORRALERO",
    "GANADERIA",
    "HERBICIDA",
    "LABRADORA",
  ],
  toys: [
    // 3-letter
    "ARO",
    "OSO",
    "YOY",
    // 4-letter
    "CUBO",
    "DADO",
    "KITE",
    "LEGO",
    "MODA",
    "ROBO",
    "SOGA",
    "TREN",
    "YOYO",
    // 5-letter
    "AVION",
    "BALDE",
    "BARCO",
    "CARPA",
    "CARRO",
    "DARDO",
    "GLOBO",
    "JUEGO",
    "OSITO",
    "PATIN",
    "PLAYA",
    "ROBOT",
    "VIDEO",
    // 6-letter
    "BARBIE",
    "CANICA",
    "COMETA",
    "CUERDA",
    "DOMINO",
    "ESPADA",
    "FIGURA",
    "FUTBOL",
    "MUNECO",
    "PELOTA",
    "PUZZLE",
    "TROMPO",
    // 7-letter
    "AJEDREZ",
    "BLOQUES",
    "CARRITO",
    "CONSOLA",
    "DISFRAZ",
    "JUGUETE",
    "PATINES",
    "PELUCHE",
    "PINTURA",
    "RESORTE",
    "VOLADOR",
    // 8-letter
    "BURBUJAS",
    "CARRERAS",
    "COLUMPIO",
    "MECEDORA",
    "PELUCHES",
    // 9-letter
    "ACROBACIA",
    "AUTOPISTA",
    "BICICLETA",
    "CABALLITO",
    "COLECCION",
    "COLUMPIOS",
    "DISFRACES",
    "MARIONETA",
    "PATINETES",
  ],
  spices: [
    // 3-letter
    "SAL",
    // 4-letter
    "ANIS",
    "MIEL",
    "NATA",
    "NUEZ",
    "SOJA",
    // 5-letter
    "ANETO",
    "AROMA",
    "CHILE",
    "CLAVO",
    "CURRY",
    "MENTA",
    "SABOR",
    "SALSA",
    // 6-letter
    "ACHOTE",
    "CANELA",
    "CAYENA",
    "COMINO",
    "ENELDO",
    "HINOJO",
    "LAUREL",
    "ROMERO",
    "SALVIA",
    // 7-letter
    "AZAFRAN",
    "MOSTAZA",
    "OREGANO",
    "PAPRIKA",
    "PEREJIL",
    "TOMILLO",
    // 8-letter
    "AJONJOLI",
    "ALBAHACA",
    "CILANTRO",
    "CINNAMON",
    "ESPECIAS",
    "ESTRAGON",
    "JENGIBRE",
    "MEJORANA",
    "PIMENTON",
    "PIMIENTA",
    "VAINILLA",
    // 9-letter
    "ALCARAVEA",
    "AROMATICO",
    "CARDAMOMO",
    "CEBOLLINO",
    "ESPECIADO",
    "GUINDILLA",
    "RALLADURA",
    "SAZONADOR",
  ],
  metals: [
    // 3-letter
    "ORO",
    // 4-letter
    "LATA",
    "ZINC",
    // 5-letter
    "ACERO",
    "COBRE",
    "CROMO",
    "METAL",
    "PLATA",
    "PLOMO",
    // 6-letter
    "BRONCE",
    "CADMIO",
    "DORADO",
    "FORJAR",
    "HIERRO",
    "LAMINA",
    "NIQUEL",
    "SOLDAR",
    // 7-letter
    "COBALTO",
    "CROMADO",
    "FERROSO",
    "FUNDIDO",
    "MINERAL",
    "PLATINO",
    "TITANIO",
    "VANADIO",
    // 8-letter
    "ALUMINIO",
    "BLINDAJE",
    "LAMINADO",
    "MAGNESIO",
    "MERCURIO",
    "PLATEADO",
    // 9-letter
    "ESMALTADO",
    "FUNDIDORA",
    "NIQUELADO",
    "SOLDADURA",
    "TUNGSTENO",
  ],
  accessories: [
    // 3-letter
    "ARO",
    "PIN",
    // 4-letter
    "ANEL",
    "CHAL",
    "CLIP",
    "DIJE",
    "GAFA",
    "GEMA",
    "JOYA",
    "LAZO",
    "PINA",
    "VELO",
    // 5-letter
    "BANDA",
    "BOLSA",
    "BOLSO",
    "CINTO",
    "FULAR",
    "GAFAS",
    "GORRA",
    "LENTE",
    "PERLA",
    "RELOJ",
    "TIARA",
    // 6-letter
    "ANILLO",
    "ARETES",
    "BROCHE",
    "CADENA",
    "COLLAR",
    "CORONA",
    "GUANTE",
    "TOCADO",
    "VISERA",
    // 7-letter
    "ALFILER",
    "AMULETO",
    "BANDANA",
    "BUFANDA",
    "CAMAFEO",
    "CARTERA",
    "CORBATA",
    "DIADEMA",
    "ESCLAVA",
    "GEMELOS",
    "HEBILLA",
    "PASADOR",
    "PEINETA",
    "PULSERA",
    "SORTIJA",
    // 8-letter
    "ABALORIO",
    "ANTEOJOS",
    "ARRACADA",
    "COLGANTE",
    "MEDALLON",
    "MONEDERO",
    "PULSERAS",
    "ZARCILLO",
    // 9-letter
    "ACCESORIO",
    "BANDOLERA",
    "BILLETERA",
    "BRACELETE",
    "BRAZALETE",
    "COLGANTES",
    "MANCUERNA",
    "PASADORES",
    "PENDIENTE",
    "PRENDEDOR",
    "SOMBRILLA",
  ],
  shapes: [
    // 3-letter
    "ARO",
    // 4-letter
    "ARCO",
    "CONO",
    "CUBO",
    "GIRO",
    "LADO",
    "ONDA",
    "OVAL",
    "PICO",
    // 5-letter
    "CURVA",
    "FORMA",
    "LINEA",
    "OVALO",
    "PLANO",
    "PUNTO",
    "RADIO",
    "ROMBO",
    "TRAZO",
    // 6-letter
    "ANGULO",
    "ARISTA",
    "CONICO",
    "CUERPO",
    "CURVAS",
    "ELIPSE",
    "ESFERA",
    "FIGURA",
    "ORBITA",
    "PRISMA",
    // 7-letter
    "ANGULOS",
    "CIRCULO",
    "ESPIRAL",
    "VERTICE",
    // 8-letter
    "CILINDRO",
    "CIRCULAR",
    "CONTORNO",
    "CUADRADO",
    "DIAGONAL",
    "ESFERICO",
    "ESTRELLA",
    "HEXAGONO",
    "PARALELO",
    "PIRAMIDE",
    "POLIGONO",
    "ROMBOIDE",
    "SIMETRIA",
    // 9-letter
    "BISECTRIZ",
    "DECAGONAL",
    "HEPTAGONO",
    "HEXAGONAL",
    "OCTAGONAL",
    "OCTOGONAL",
    "PENTAGONO",
    "PIRAMIDAL",
    "POLIGONAL",
    "ROMBOIDAL",
    "SIMETRICO",
  ],
  feelings: [
    // 3-letter
    "IRA",
    "PAZ",
    // 4-letter
    "AMOR",
    "BIEN",
    "DUDA",
    "GOZO",
    "LUTO",
    "ODIO",
    "PENA",
    "RISA",
    // 5-letter
    "ANIMO",
    "CALMA",
    "CELOS",
    "CULPA",
    "DESEO",
    "DICHA",
    "ENOJO",
    "EXITO",
    "FELIZ",
    "FURIA",
    "GUSTO",
    "HUMOR",
    "MIEDO",
    "PESAR",
    "RABIA",
    "SUSTO",
    "TEMOR",
    "VALOR",
    // 6-letter
    "AFECTO",
    "ALIVIO",
    "BONDAD",
    "CARINO",
    "CORAJE",
    "HORROR",
    "PASION",
    "PLACER",
    "RENCOR",
    // 7-letter
    "ADMIRAR",
    "ALEGRIA",
    "AMISTAD",
    "APRECIO",
    "ASOMBRO",
    "EMPATIA",
    "ENVIDIA",
    "EUFORIA",
    "ORGULLO",
    "RESPETO",
    "SOLEDAD",
    "TENSION",
    "TERNURA",
    // 8-letter
    "ANGUSTIA",
    "ANSIEDAD",
    "CONFIADO",
    "DESANIMO",
    "FASTIDIO",
    "GRATITUD",
    "HUMILDAD",
    "SORPRESA",
    "TRISTEZA",
    "VALENTIA",
    // 9-letter
    "COMPASION",
    "CONFIANZA",
    "DESPRECIO",
    "ESPERANZA",
    "FELICIDAD",
    "NOSTALGIA",
    "OPTIMISMO",
    "OPTIMISTA",
    "PACIENCIA",
    "PESIMISMO",
    "PESIMISTA",
    "SERENIDAD",
    "TRANQUILO",
    "VERGUENZA",
  ],
  water: [
    // 3-letter
    "MAR",
    "OLA",
    "RIO",
    // 4-letter
    "AGUA",
    "BOTE",
    "CABO",
    "FARO",
    "GOTA",
    "LAGO",
    "NAVE",
    "POZA",
    "ROCA",
    // 5-letter
    "BAHIA",
    "BALSA",
    "BUCEO",
    "CANAL",
    "CAUCE",
    "COSTA",
    "DELTA",
    "DIQUE",
    "GOLFO",
    "HIELO",
    "MAREA",
    "NADAR",
    "NIEVE",
    "PLAYA",
    "PRESA",
    "VAPOR",
    // 6-letter
    "ARROYO",
    "CHARCA",
    "FUENTE",
    "GEISER",
    "LAGUNA",
    "LLUVIA",
    "MARINO",
    "OLEAJE",
    "ORILLA",
    "RIBERA",
    // 7-letter
    "ACEQUIA",
    "CASCADA",
    "DILUVIO",
    "EMBALSE",
    "GLACIAR",
    "HUMEDAD",
    "LAGUNAS",
    "MANGLAR",
    "PANTANO",
    "REPRESA",
    // 8-letter
    "ACUIFERO",
    "AFLUENTE",
    "AGUACERO",
    "ARRECIFE",
    "CASCADAS",
    "CATARATA",
    "CISTERNA",
    "EMBALSES",
    "ESTANQUE",
    "ESTUARIO",
    "MAREJADA",
    "MARISMAS",
    "OCEANICO",
    "PANTANOS",
    "REMOLINO",
    "TORRENTE",
    // 9-letter
    "AFLUENTES",
    "CATARATAS",
    "CORRIENTE",
    "GLACIALES",
    "HUMEDALES",
    "MANANTIAL",
    "NAVEGABLE",
    "REMOLINOS",
    "RIACHUELO",
    "TORRENTES",
  ],
  mountains: [
    // 3-letter
    "PIE",
    "RIO",
    "SOL",
    // 4-letter
    "ALPE",
    "ALTO",
    "CIMA",
    "LAGO",
    "LOMA",
    "META",
    "MINA",
    "NUBE",
    "PASO",
    "PICO",
    "PINO",
    "ROCA",
    "RUTA",
    // 5-letter
    "CAMPO",
    "CERRO",
    "CIELO",
    "CLIMA",
    "CUEVA",
    "FALDA",
    "FAUNA",
    "FLORA",
    "LLANO",
    "MONTE",
    "NIEVE",
    "NORTE",
    "PRADO",
    "SELVA",
    "SENDA",
    "SUELO",
    "VALLE",
    "VISTA",
    // 6-letter
    "ABISMO",
    "ALPINO",
    "ALTURA",
    "ANDINO",
    "BOSQUE",
    "CAMINO",
    "CANTON",
    "COLINA",
    "CRESTA",
    "CUMBRE",
    "GRIETA",
    "HELADO",
    "LADERA",
    "MESETA",
    "NEVADO",
    "PIEDRA",
    "ROCOSO",
    "SIERRA",
    "VIENTO",
    // 7-letter
    "ASCENSO",
    "BOSQUES",
    "CASCADA",
    "CAVERNA",
    "CORDOBA",
    "EROSION",
    "GLACIAL",
    "GLACIAR",
    "GRANITO",
    "MIRADOR",
    "MONTANA",
    "PAISAJE",
    "PRADERA",
    "REFUGIO",
    "ROCOSAS",
    "SENDERO",
    "TERRENO",
    // 8-letter
    "ACAMPADA",
    "AVENTURA",
    "BARRANCO",
    "CASCADAS",
    "DESIERTO",
    "ESCALADA",
    "FRONTERA",
    "PANORAMA",
    "TRAVESIA",
    "TREKKING",
    "VENTISCA",
    // 9-letter
    "ALPINISMO",
    "ALPINISTA",
    "ALTIPLANO",
    "AVALANCHA",
    "ELEVACION",
    "ESCALADOR",
  ],
  seafood: [
    // 3-letter
    "MAR",
    "PEZ",
    "SAL",
    // 4-letter
    "ALGA",
    "ATUN",
    "CEBO",
    "MERO",
    "RAPE",
    "SOPA",
    // 5-letter
    "CORAL",
    "GAMBA",
    "OSTRA",
    "PARGO",
    "PERCA",
    "PULPO",
    // 6-letter
    "ALMEJA",
    "ANCHOA",
    "BESUGO",
    "BONITO",
    "CAVIAR",
    "CIGALA",
    "COCINA",
    "DORADA",
    "FILETE",
    "FRESCO",
    "GAMBAS",
    "LUBINA",
    "MUELLE",
    "NAVAJA",
    "OSTRAS",
    "SALMON",
    "TRUCHA",
    "VIEIRA",
    // 7-letter
    "ABADEJO",
    "ACUARIO",
    "ANCHOAS",
    "ARENQUE",
    "BACALAO",
    "CABALLA",
    "CALAMAR",
    "CEVICHE",
    "CIGALAS",
    "MARISCO",
    "MERLUZA",
    "PERCEBE",
    "PESCADO",
    "PLATIJA",
    "SARDINA",
    // 8-letter
    "CANGREJO",
    "CENTOLLO",
    "LANGOSTA",
    "LENGUADO",
    "MARISCOS",
    "MEJILLON",
    "PESCADOR",
    "SARDINAS",
    // 9-letter
    "BOGAVANTE",
    "CALAMARES",
    "CAMARONES",
    "CANGREJOS",
    "CRUSTACEO",
    "LANGOSTAS",
    "RODABALLO",
  ],
  camping: [
    // 3-letter
    "OLA",
    "OSO",
    "RIO",
    "SOL",
    // 4-letter
    "AGUA",
    "ASAR",
    "BOTA",
    "FARO",
    "LUNA",
    "MAPA",
    "PINO",
    "ROCA",
    "SACO",
    "SOGA",
    // 5-letter
    "ARBOL",
    "BRASA",
    "CANOA",
    "CARPA",
    "CUEVA",
    "FAUNA",
    "FUEGO",
    "HACHA",
    "KAYAK",
    "NOCHE",
    "PESCA",
    // 6-letter
    "BOSQUE",
    "CABANA",
    "CAMINO",
    "COMIDA",
    "CUERDA",
    "DORMIR",
    "EQUIPO",
    "ESTUFA",
    "FOGATA",
    "HAMACA",
    "NATURA",
    "TIENDA",
    // 7-letter
    "ACAMPAR",
    "CAMINAR",
    "COCINAR",
    "COLCHON",
    "HOGUERA",
    "HUMEDAD",
    "LAMPARA",
    "MOCHILA",
    "NAVEGAR",
    "REFUGIO",
    "SENDERO",
    // 8-letter
    "ACAMPADA",
    "AVENTURA",
    "BARBACOA",
    "CAMPISMO",
    "CAMPISTA",
    "CARAVANA",
    "EXPLORAR",
    "FRONTERA",
    "LINTERNA",
    "TRAVESIA",
    // 9-letter
    "ACAMPADAS",
    "EXCURSION",
    "MOCHILERO",
    "PERNOCTAR",
  ],
  circus: [
    // 3-letter
    "RED",
    "VOZ",
    // 4-letter
    "ACTO",
    "ARCO",
    "BOLA",
    "CAPA",
    "DOMA",
    "FILA",
    "GIRA",
    "LEON",
    "MAGO",
    "MONO",
    "PALO",
    "REJA",
    "RISA",
    "SHOW",
    "TIRO",
    // 5-letter
    "BANDA",
    "CARPA",
    "CIRCO",
    "CLOWN",
    "DOMAR",
    "FIERA",
    "GLOBO",
    "JAULA",
    "MAGIA",
    "PISTA",
    "SALTO",
    "TIGRE",
    "TRUCO",
    // 6-letter
    "ESCENA",
    "MUSICA",
    "NUMERO",
    "PAYASO",
    // 7-letter
    "ARTISTA",
    "ASIENTO",
    "DOMADOR",
    "FUNCION",
    "PAYASOS",
    "PIRUETA",
    "PUBLICO",
    // 8-letter
    "ACROBATA",
    "ANIMALES",
    "ELEFANTE",
    "PIRUETAS",
    "TRAPECIO",
    // 9-letter
    "ACROBACIA",
    "ATRACCION",
    "CARROMATO",
    "ELEFANTES",
    "MALABARES",
  ],
  pirates: [
    // 3-letter
    "MAR",
    "ORO",
    "RON",
    // 4-letter
    "BOTE",
    "CABO",
    "FARO",
    "ISLA",
    "MAPA",
    "NAVE",
    "PALO",
    "PROA",
    "REMO",
    "VELA",
    // 5-letter
    "ANCLA",
    "BARCO",
    "BOTIN",
    "BUQUE",
    "CANON",
    "COFRE",
    "COSTA",
    "FLOTA",
    "JOLLY",
    "MOTIN",
    "SABLE",
    "TIMON",
    // 6-letter
    "CARIBE",
    "ESPADA",
    "GALEON",
    "GARFIO",
    "PARCHE",
    "PIRATA",
    "SAQUEO",
    "TESORO",
    // 7-letter
    "BANDERA",
    "BANDIDO",
    "CAPITAN",
    "ESCAPAR",
    "ESPADAS",
    "FRAGATA",
    "NAVEGAR",
    "PILLAJE",
    "RESCATE",
    "SAQUEAR",
    "TABERNA",
    "TIBURON",
    // 8-letter
    "ABORDAJE",
    "AVENTURA",
    "BUCANERO",
    "CALAVERA",
    "CORSARIO",
    "MARINERO",
    "NAUFRAGO",
    // 9-letter
    "BERGANTIN",
    "BUCANEROS",
    "CORSARIOS",
    "MARINEROS",
    "NAUFRAGIO",
    "NAVEGANTE",
    "PIRATERIA",
  ],
  castle: [
    // 3-letter
    "REY",
    "SIR",
    // 4-letter
    "ARCO",
    "CAPA",
    "DAMA",
    "FOSO",
    "LORD",
    "MURO",
    "PAJE",
    "REJA",
    "SALA",
    "SEDA",
    "VINO",
    // 5-letter
    "BARON",
    "BUFON",
    "CORTE",
    "DUQUE",
    "JUSTA",
    "LANZA",
    "MONJE",
    "NOBLE",
    "REINA",
    "REINO",
    "TORRE",
    "TRONO",
    // 6-letter
    "ALMENA",
    "CORONA",
    "DRAGON",
    "ESCUDO",
    "ESPADA",
    "FEUDAL",
    "PUENTE",
    "SIERVO",
    "TORNEO",
    // 7-letter
    "ALMENAS",
    "BANDERA",
    "BASTION",
    "BATALLA",
    "CAPILLA",
    "CRUZADA",
    "DUNGEON",
    "HERALDO",
    "MURALLA",
    "PALACIO",
    "REINADO",
    "VASALLO",
    // 8-letter
    "ALQUIMIA",
    "ARMADURA",
    "BANQUETE",
    "CASTILLO",
    "EJERCITO",
    "ESCUDERO",
    "MEDIEVAL",
    "MURALLAS",
    "PRINCESA",
    "PRINCIPE",
    // 9-letter
    "ARMADURAS",
    "CABALLERO",
    "CASTILLOS",
    "CATAPULTA",
    "FORTALEZA",
    "HERALDICA",
  ],
  jungle: [
    // 3-letter
    "AVE",
    "BOA",
    "SOL",
    // 4-letter
    "ALGA",
    "HOJA",
    "LODO",
    "MONO",
    "NIDO",
    "PUMA",
    "RAIZ",
    "RANA",
    "SOGA",
    // 5-letter
    "ARBOL",
    "BAMBU",
    "BARRO",
    "BRUMA",
    "CALOR",
    "CLIMA",
    "DENSO",
    "FAUNA",
    "FLORA",
    "FRUTA",
    "LIANA",
    "MANGO",
    "PITON",
    "SELVA",
    "TIGRE",
    "VAPOR",
    "VERDE",
    // 6-letter
    "ANIMAL",
    "BOSQUE",
    "CANOPY",
    "GORILA",
    "HUMEDO",
    "IGUANA",
    "JAGUAR",
    "LIANAS",
    "LLUVIA",
    "PLANTA",
    "TRONCO",
    // 7-letter
    "CASCADA",
    "EXOTICO",
    "FOLLAJE",
    "HABITAT",
    "HUMEDAD",
    "INSECTO",
    "PALMERA",
    "PANTERA",
    "TROPICO",
    // 8-letter
    "AMAZONAS",
    "ANACONDA",
    "AVENTURA",
    "ECOLOGIA",
    "INSECTOS",
    "LEOPARDO",
    "LLUVIOSO",
    "ORQUIDEA",
    "TROPICAL",
    // 9-letter
    "COCODRILO",
    "ORANGUTAN",
    "SERPIENTE",
  ],
  desert: [
    // 3-letter
    "SOL",
    // 4-letter
    "DUNA",
    "ROCA",
    "SECO",
    // 5-letter
    "ARIDO",
    "CALOR",
    "CLIMA",
    "DUNAS",
    "OASIS",
    "POLVO",
    // 6-letter
    "ARENAS",
    "CACTUS",
    "COYOTE",
    "MIRAGE",
    "NOMADA",
    "REPTIL",
    "SAHARA",
    "SEQUIA",
    "SOMBRA",
    "VIBORA",
    "VIENTO",
    // 7-letter
    "BEDUINO",
    "CAMELLO",
    "LAGARTO",
    "PAISAJE",
    "PIEDRAS",
    // 8-letter
    "CAMELLOS",
    "CARAVANA",
    "DESIERTO",
    "DESOLADO",
    "REPTILES",
    "TORMENTA",
    // 9-letter
    "CARAVANAS",
    "ESCORPION",
    "ESPEJISMO",
    "HORIZONTE",
    "LAGARTIJA",
    "SERPIENTE",
  ],
  arctic: [
    // 3-letter
    "OSO",
    "SOL",
    // 4-letter
    "FOCA",
    "FRIO",
    "IGLU",
    "LOBO",
    "ORCA",
    "POLO",
    "RENO",
    // 5-letter
    "BRUMA",
    "HIELO",
    "HUSKY",
    "INUIT",
    "MORSA",
    "NIEVE",
    "NORTE",
    "POLAR",
    // 6-letter
    "ARTICO",
    "AURORA",
    "BLANCO",
    "CARIBU",
    "HELADO",
    "NARVAL",
    "TRINEO",
    "TUNDRA",
    // 7-letter
    "BALLENA",
    "GLACIAR",
    "ICEBERG",
    // 8-letter
    "BALLENAS",
    "BLIZZARD",
    "ESQUIMAL",
    "INVIERNO",
    "PINGUINO",
    "TORMENTA",
    "VENTISCA",
    // 9-letter
    "ANTARTICO",
    "CONGELADO",
    "GLACIARES",
    "MIGRACION",
    "PINGUINOS",
  ],
  carnival: [
    // 3-letter
    "REY",
    // 5-letter
    "BAILE",
    "BANDA",
    "CARRO",
    "COLOR",
    "DANZA",
    "GLOBO",
    "JUEGO",
    "LUCES",
    "MAGIA",
    "MURGA",
    "REINA",
    "RITMO",
    "SAMBA",
    "TRAJE",
    // 6-letter
    "BRILLO",
    "FIESTA",
    "JUEGOS",
    "MUSICA",
    "PLUMAS",
    "PREMIO",
    // 7-letter
    "ALEGRIA",
    "CARROZA",
    "CONFETI",
    "DESFILE",
    "MASCARA",
    "MUSICOS",
    // 8-letter
    "BAILARIN",
    "BATUCADA",
    "CARNAVAL",
    "CARROZAS",
    "COMPARSA",
    "DANZARIN",
    "FANTASIA",
    "FESTIVAL",
    "MASCARAS",
    "ORQUESTA",
    // 9-letter
    "BAILARINA",
    "COMPARSAS",
  ],
};
