import type { ThemeId } from "../../utils/themes";

export const fr: Record<ThemeId, string[]> = {
  animals: [
    // 3-letter
    "ANE",
    "COQ",
    "OIE",
    "RAT",
    "VER",
    // 4-letter
    "CERF",
    "CHAT",
    "FAON",
    "LION",
    "LOUP",
    "OURS",
    "PUMA",
    "RATS",
    "VEAU",
    // 5-letter
    "AIGLE",
    "BICHE",
    "CHIEN",
    "COBRA",
    "CRABE",
    "KOALA",
    "LAPIN",
    "MORSE",
    "PANDA",
    "POULE",
    "SINGE",
    "TAUPE",
    "TIGRE",
    "VACHE",
    "ZEBRE",
    // 6-letter
    "BUFFLE",
    "CANARD",
    "CASTOR",
    "CHACAL",
    "CHEVAL",
    "CHEVRE",
    "GIRAFE",
    "JAGUAR",
    "LEZARD",
    "LOUTRE",
    "MOUTON",
    "OTARIE",
    "PIGEON",
    "RENARD",
    "SOURIS",
    "TORTUE",
    // 7-letter
    "BALEINE",
    "BELETTE",
    "CANICHE",
    "CHAMEAU",
    "DAUPHIN",
    "FOURMIS",
    "GAZELLE",
    "GORILLE",
    "HAMSTER",
    "LEOPARD",
    "POISSON",
    "SERPENT",
    // 8-letter
    "ANTILOPE",
    "AUTRUCHE",
    "CAMELEON",
    "ECUREUIL",
    "ELEPHANT",
    "HERISSON",
    "PANTHERE",
    "PAPILLON",
    "PINGOUIN",
    // 9-letter
    "CHIMPANZE",
    "CROCODILE",
    "KANGOUROU",
    "PERROQUET",
  ],
  food: [
    // 3-letter
    "BLE",
    "LIN",
    "MIE",
    "OIE",
    "RIZ",
    "THE",
    // 4-letter
    "BRIE",
    "CAFE",
    "LAIT",
    "MAIS",
    "NOIX",
    "OEUF",
    "PAIN",
    "PATE",
    "POIS",
    "PORC",
    // 5-letter
    "BACON",
    "BOEUF",
    "CACAO",
    "CRABE",
    "CREME",
    "CREPE",
    "DINDE",
    "FIGUE",
    "FRUIT",
    "HUILE",
    "MELON",
    "MOULE",
    "OLIVE",
    "POIRE",
    "POMME",
    "PRUNE",
    "SUCRE",
    "TARTE",
    // 6-letter
    "AMANDE",
    "ANANAS",
    "AVOCAT",
    "BANANE",
    "BEURRE",
    "CANARD",
    "CERISE",
    "CITRON",
    "COOKIE",
    "CROUTE",
    "ECLAIR",
    "FRAISE",
    "GATEAU",
    "HOMARD",
    "JAMBON",
    "LAITUE",
    "LEGUME",
    "OIGNON",
    "ORANGE",
    "PATATE",
    "POULET",
    "RAISIN",
    "SALADE",
    "TOMATE",
    "VIANDE",
    "YAOURT",
    // 7-letter
    "ABRICOT",
    "ASPERGE",
    "BISCUIT",
    "BRIOCHE",
    "CALAMAR",
    "CARAMEL",
    "CAROTTE",
    "EPINARD",
    "FROMAGE",
    "PANCAKE",
    "POISSON",
    // 8-letter
    "BAGUETTE",
    "BROCCOLI",
    "CHOCOLAT",
    "CREVETTE",
    "NOISETTE",
    "OMELETTE",
    "SANDWICH",
    "SAUCISSE",
    // 9-letter
    "ARTICHAUT",
    "AUBERGINE",
    "COURGETTE",
    "CROISSANT",
    "FRAMBOISE",
    "SPAGHETTI",
  ],
  fruits: [
    // 4-letter
    "KIWI",
    "MURE",
    "NOIX",
    // 5-letter
    "DATTE",
    "FIGUE",
    "FRUIT",
    "MELON",
    "OLIVE",
    "PECHE",
    "POIRE",
    "POMME",
    "PRUNE",
    // 6-letter
    "AMANDE",
    "ANANAS",
    "AVOCAT",
    "BANANE",
    "CASSIS",
    "CERISE",
    "CITRON",
    "FRAISE",
    "GOYAVE",
    "LITCHI",
    "MANGUE",
    "ORANGE",
    "PAPAYE",
    "POMELO",
    "RAISIN",
    // 7-letter
    "ABRICOT",
    "AIRELLE",
    "GRENADE",
    // 8-letter
    "MYRTILLE",
    "NOISETTE",
    "PASTEQUE",
    "PISTACHE",
    // 9-letter
    "FRAMBOISE",
    "GRENADINE",
    "MANDARINE",
    "NECTARINE",
  ],
  colors: [
    // 4-letter
    "BLEU",
    "BRUN",
    "GRIS",
    "JADE",
    "NOIR",
    "ROSE",
    "VERT",
    // 5-letter
    "BEIGE",
    "BLANC",
    "CREME",
    "JAUNE",
    "MAUVE",
    "OLIVE",
    "PECHE",
    "ROUGE",
    "SABLE",
    // 6-letter
    "ARGENT",
    "AVOCAT",
    "BRONZE",
    "CARMIN",
    "CERISE",
    "CITRON",
    "CORAIL",
    "CUIVRE",
    "INDIGO",
    "IVOIRE",
    "MARRON",
    "ORANGE",
    "SAPHIR",
    "SAUMON",
    "VIOLET",
    // 7-letter
    "ABRICOT",
    "CELADON",
    "CHAMOIS",
    "CHARBON",
    "FUCHSIA",
    "LAVANDE",
    "MAGENTA",
    "POURPRE",
    // 8-letter
    "AMARANTE",
    "BORDEAUX",
    "CANNELLE",
    "CHOCOLAT",
    "ECARLATE",
    "EMERAUDE",
    "NOISETTE",
    // 9-letter
    "AUBERGINE",
    "BOURGOGNE",
    "CHAMPAGNE",
    "TURQUOISE",
    "VERMILLON",
  ],
  body: [
    // 3-letter
    "COU",
    "DOS",
    "NEZ",
    "OIE",
    "ONG",
    // 4-letter
    "BRAS",
    "DENT",
    "FOIE",
    "JOUE",
    "MAIN",
    "OEIL",
    "PEAU",
    "PIED",
    "REIN",
    "SANG",
    "SEIN",
    "TETE",
    // 5-letter
    "BOCHE",
    "COEUR",
    "COUDE",
    "CRANE",
    "DENTS",
    "DOIGT",
    "FRONT",
    "GENOU",
    "GORGE",
    "JAMBE",
    "LEVRE",
    "NOEUD",
    "NUQUE",
    "ONGLE",
    "TORSE",
    "VEINE",
    // 6-letter
    "ARTERE",
    "BASSIN",
    "BOUCHE",
    "EPAULE",
    "LANGUE",
    "MOLLET",
    "MUSCLE",
    "ORTEIL",
    "POUMON",
    "TENDON",
    "VENTRE",
    "VISAGE",
    // 7-letter
    "ABDOMEN",
    "CERVEAU",
    "COLONNE",
    "ESTOMAC",
    "HANCHES",
    "POIGNET",
    // 8-letter
    "CHEVILLE",
    "INTESTIN",
    "LIGAMENT",
    "LOMBAIRE",
    "MACHOIRE",
    "OMOPLATE",
    "OSSATURE",
    "OSSEMENT",
    "PANCREAS",
    "POITRINE",
    "VERTEBRE",
    // 9-letter
    "CLAVICULE",
    "OESOPHAGE",
    "SQUELETTE",
  ],
  family: [
    // 3-letter
    "NOM",
    // 4-letter
    "BEBE",
    "FILS",
    "MERE",
    "PAPA",
    "PAPY",
    "PERE",
    // 5-letter
    "BELLE",
    "EPOUX",
    "FEMME",
    "FILLE",
    "FRERE",
    "HOMME",
    "MAMAN",
    "MAMIE",
    "NEVEU",
    "NIECE",
    "ONCLE",
    "SOEUR",
    "TANTE",
    // 6-letter
    "COUSIN",
    "ENFANT",
    "EPOUSE",
    "GRANDS",
    "JUMEAU",
    "MADAME",
    "PARENT",
    // 7-letter
    "ANCETRE",
    "COUSINE",
    "DIVORCE",
    "FAMILLE",
    "FIANCEE",
    "JUMEAUX",
    "JUMELLE",
    "MARIAGE",
    "PARENTS",
    "PARRAIN",
    // 8-letter
    "ADOPTION",
    "ALLIANCE",
    "ANCETRES",
    "BEAUFILS",
    "HERITAGE",
    "MARRAINE",
    // 9-letter
    "NAISSANCE",
  ],
  clothing: [
    // 3-letter
    "SAC",
    // 4-letter
    "CAPE",
    "GANT",
    "JEAN",
    "JUPE",
    "PULL",
    "ROBE",
    "SLIP",
    "SOIE",
    // 5-letter
    "BERET",
    "BIJOU",
    "BOTTE",
    "CHALE",
    "ETOLE",
    "GILET",
    "SHORT",
    "TENUE",
    "TUQUE",
    "VESTE",
    // 6-letter
    "ANORAK",
    "BLOUSE",
    "BONNET",
    "BOUCLE",
    "BOUTON",
    "MOUFLE",
    "PYJAMA",
    "SANDAL",
    "TRICOT",
    // 7-letter
    "BLOUSON",
    "BUSTIER",
    "CALECON",
    "CHAPEAU",
    "CHEMISE",
    "COLLANT",
    "COSTUME",
    "CRAVATE",
    "ECHARPE",
    "FOULARD",
    "JUPETTE",
    "MAILLOT",
    "MANTEAU",
    "SANDALE",
    "SMOKING",
    "SOULIER",
    "VELOURS",
    // 8-letter
    "BERMUDAS",
    "CARDIGAN",
    "CEINTURE",
    "CHANDAIL",
    "JAMBIERE",
    "PANTALON",
    "PEIGNOIR",
    "PULLOVER",
    "TAILLEUR",
    "UNIFORME",
    // 9-letter
    "CASQUETTE",
    "CHAUSSURE",
    "CHEMISIER",
    "COMBIZONE",
    "DEBARDEUR",
    "ESCARPINS",
    "MANCHETTE",
    "PANTOUFLE",
    "PARDESSUS",
  ],
  kitchen: [
    // 3-letter
    "BOL",
    "POT",
    // 4-letter
    "FOUR",
    // 5-letter
    "FOUET",
    "FRIGO",
    "POELE",
    "ROBOT",
    "TABLE",
    "TASSE",
    "VERRE",
    // 6-letter
    "CONGEL",
    "LOUCHE",
    "MIXEUR",
    "PLAQUE",
    "TIROIR",
    // 7-letter
    "BATTEUR",
    "COCOTTE",
    "COUTEAU",
    "CUILLER",
    "HACHOIR",
    "MARMITE",
    "PLANCHE",
    "SPATULE",
    "THEIERE",
    "TORCHON",
    // 8-letter
    "ASSIETTE",
    "COCOTTES",
    "COUVERTS",
    "CUILLERE",
    "PASSOIRE",
    "POIVRIER",
    "SALADIER",
    "SAUCIERE",
    // 9-letter
    "CAFETIERE",
    "CASSEROLE",
    "EGOUTTOIR",
    "ENTONNOIR",
    "MICROONDE",
    "PLONGEOIR",
    "POIVRIERE",
    "VAISSELLE",
  ],
  school: [
    // 3-letter
    "BIC",
    "SAC",
    // 4-letter
    "BANC",
    "COUR",
    "NOTE",
    "TEST",
    // 5-letter
    "ATLAS",
    "CARTE",
    "COLLE",
    "COURS",
    "CRAIE",
    "GOMME",
    "LECON",
    "LIVRE",
    "NOTES",
    "STYLO",
    "TABLE",
    // 6-letter
    "AGENDA",
    "BUREAU",
    "CAHIER",
    "CALCUL",
    "CHAISE",
    "CLASSE",
    "COMPAS",
    "COPAIN",
    "CRAYON",
    "DESSIN",
    "DEVOIR",
    "ETUDES",
    "EXAMEN",
    "FEUTRE",
    "MANUEL",
    "PAPIER",
    // 7-letter
    "ARDOISE",
    "CALCULS",
    "CANTINE",
    "CISEAUX",
    "COLLEGE",
    "CRAYONS",
    "DEVOIRS",
    "DIPLOME",
    "GLOBALE",
    "GYMNASE",
    "LECTURE",
    "MUSIQUE",
    "PUNAISE",
    "TABLEAU",
    "TROUSSE",
    // 8-letter
    "BIOLOGIE",
    "CLASSEUR",
    "COMPTINE",
    "HISTOIRE",
    "PEINTURE",
    "PHYSIQUE",
    "PRIMAIRE",
    "SCIENCES",
    // 9-letter
    "DIRECTEUR",
    "EDUCATION",
    "GRAMMAIRE",
    "MAITRESSE",
  ],
  garden: [
    // 3-letter
    "PIN",
    "PRE",
    // 4-letter
    "BOIS",
    "HAIE",
    "IRIS",
    "ORME",
    "PARC",
    "ROSE",
    "TIGE",
    // 5-letter
    "ARBRE",
    "BULBE",
    "FLEUR",
    "GAZON",
    "HERBE",
    "PELLE",
    "SAPIN",
    "SAULE",
    "SEMIS",
    "TERRE",
    "VIGNE",
    // 6-letter
    "BAMBOU",
    "DAHLIA",
    "GRAINE",
    "JARDIN",
    "JASMIN",
    "LIERRE",
    "MUGUET",
    "PLANTE",
    "RACINE",
    "ROSIER",
    "TULIPE",
    // 7-letter
    "ARBUSTE",
    "BRANCHE",
    "COMPOST",
    "ENGRAIS",
    "FEUILLE",
    "LAVANDE",
    "PELOUSE",
    "PIVOINE",
    "POTAGER",
    "TERREAU",
    // 8-letter
    "ARROSEUR",
    "ARROSOIR",
    "BROUETTE",
    "CISAILLE",
    "FONTAINE",
    "HIBISCUS",
    "JACINTHE",
    "LAVANDIN",
    "MAGNOLIA",
    "VIOLETTE",
    // 9-letter
    "BROUETTES",
    "CISAILLES",
    "HORTENSIA",
    "JARDINIER",
    "JONQUILLE",
    "MAGNOLIAS",
    "TOURNESOL",
  ],
  birds: [
    // 3-letter
    "COQ",
    "OIE",
    "PIE",
    // 4-letter
    "AILE",
    "BUSE",
    "CANE",
    "GEAI",
    "GRUE",
    "NIDS",
    "PAON",
    // 5-letter
    "AIGLE",
    "CYGNE",
    "DINDE",
    "HIBOU",
    "MERLE",
    "POULE",
    // 6-letter
    "AUTOUR",
    "CANARD",
    "CONDOR",
    "COUCOU",
    "FAUCON",
    "MARTIN",
    "PIGEON",
    "PINSON",
    "TOUCAN",
    // 7-letter
    "CIGOGNE",
    "COLIBRI",
    "COLOMBE",
    "CORBEAU",
    "FLAMANT",
    "MOINEAU",
    "MOUETTE",
    "PERDRIX",
    "VAUTOUR",
    // 8-letter
    "ALOUETTE",
    "AUTRUCHE",
    "CARDINAL",
    "CORMORAN",
    "FAUVETTE",
    "MACAREUX",
    "MARTINET",
    "PERRUCHE",
    "PINGOUIN",
    // 9-letter
    "PERROQUET",
    "ROSSIGNOL",
  ],
  insects: [
    // 3-letter
    "VER",
    // 4-letter
    "MITE",
    "PUCE",
    "TAON",
    // 5-letter
    "GUEPE",
    "LARVE",
    "MANTE",
    "TIQUE",
    // 6-letter
    "BLATTE",
    "CAFARD",
    "CIGALE",
    "FOURMI",
    "FRELON",
    "MOUCHE",
    "PHASME",
    // 7-letter
    "ABEILLE",
    "BOURDON",
    "CRIQUET",
    "GRILLON",
    "LUCIOLE",
    "PUCERON",
    "PUNAISE",
    "TERMITE",
    // 8-letter
    "CHENILLE",
    "HANNETON",
    "PAPILLON",
    // 9-letter
    "DORYPHORE",
    "LIBELLULE",
    "MOUCHERON",
    "MOUSTIQUE",
  ],
  weather: [
    // 3-letter
    "AIR",
    "EAU",
    "GEL",
    // 4-letter
    "BEAU",
    "CIEL",
    "VENT",
    // 5-letter
    "BRUME",
    "CHAUD",
    "CLAIR",
    "FRAIS",
    "FROID",
    "GIVRE",
    "NEIGE",
    "NUAGE",
    "ORAGE",
    "PLUIE",
    // 6-letter
    "AVERSE",
    "FOUDRE",
    "RAFALE",
    "SOLEIL",
    "TYPHON",
    // 7-letter
    "CHALEUR",
    "CYCLONE",
    "NUAGEUX",
    "ORAGEUX",
    "OURAGAN",
    "TORNADE",
    "VERGLAS",
    // 8-letter
    "BLIZZARD",
    "CANICULE",
    "TONNERRE",
  ],
  ocean: [
    // 3-letter
    "EAU",
    "ILE",
    "MER",
    // 4-letter
    "BAIE",
    "DUNE",
    "FOND",
    "GOLF",
    "LAME",
    "PORT",
    "QUAI",
    "RAME",
    "THON",
    // 5-letter
    "ALGUE",
    "ANCRE",
    "CARGO",
    "CRABE",
    "FERRY",
    "FILET",
    "GOLFE",
    "LAGON",
    "MARIN",
    "MOULE",
    "PERLE",
    "PHARE",
    "PLAGE",
    "SABLE",
    "VAGUE",
    "VOILE",
    "YACHT",
    // 6-letter
    "BARQUE",
    "BATEAU",
    "CABINE",
    "CORAIL",
    "HARENG",
    "HOMARD",
    "MOUSSE",
    "NAVIRE",
    "REQUIN",
    // 7-letter
    "ANCHOIS",
    "BALEINE",
    "COURANT",
    "DAUPHIN",
    "FALAISE",
    "ICEBERG",
    "MOUETTE",
    "PIEUVRE",
    "SARDINE",
    // 8-letter
    "AQUARIUM",
    "BAIGNADE",
    "COQUILLE",
    "ESTUAIRE",
    "LITTORAL",
    "MARITIME",
    "NAUFRAGE",
    "NAUTIQUE",
    "PALOURDE",
    "PLONGEUR",
    // 9-letter
    "LANGOUSTE",
  ],
  sports: [
    // 3-letter
    "BUT",
    "JEU",
    "SKI",
    "TIR",
    // 4-letter
    "BOXE",
    "COUP",
    "FOOT",
    "GOLF",
    "JUDO",
    "LUGE",
    "POLO",
    "RING",
    "SAUT",
    "SURF",
    "TOUR",
    // 5-letter
    "BALLE",
    "CATCH",
    "FINAL",
    "MATCH",
    "PASSE",
    "POINT",
    "RUGBY",
    "SCORE",
    "STADE",
    "VOILE",
    // 6-letter
    "AVIRON",
    "BASKET",
    "BOXEUR",
    "COURSE",
    "HOCKEY",
    "JOUEUR",
    "NAGEUR",
    "SKIEUR",
    "SPRINT",
    "TENNIS",
    "VOLLEY",
    // 7-letter
    "ARBITRE",
    "ESCRIME",
    "GARDIEN",
    "LANCEUR",
    "PISCINE",
    // 8-letter
    "CHAMPION",
    "CYCLISME",
    "FOOTBALL",
    "GYMNASTE",
    "MARATHON",
    "NATATION",
    "PATINAGE",
    "VICTOIRE",
    // 9-letter
    "ALPINISME",
    "BADMINTON",
    "TRIATHLON",
    "VOLLEYEUR",
  ],
  music: [
    // 3-letter
    "AIR",
    "RAP",
    "SON",
    // 4-letter
    "ALTO",
    "ARIA",
    "BEAT",
    "CHEF",
    "FUNK",
    "GONG",
    "JAZZ",
    "NOTE",
    "ROCK",
    "SOLO",
    "TRIO",
    // 5-letter
    "BANJO",
    "BASSE",
    "BLUES",
    "CHANT",
    "CORDE",
    "DISCO",
    "GAMME",
    "HARPE",
    "HYMNE",
    "ORGUE",
    "PIANO",
    "POLKA",
    "RADIO",
    "SALSA",
    "SAMBA",
    "TANGO",
    "TEMPO",
    "VALSE",
    // 6-letter
    "ACCORD",
    "BASSON",
    "CHOEUR",
    "PAROLE",
    "REGGAE",
    "RYTHME",
    "SONATE",
    "STUDIO",
    "VIOLON",
    // 7-letter
    "ARTISTE",
    "BALLADE",
    "CHANSON",
    "CHORALE",
    "CLAVIER",
    "CONCERT",
    "FANFARE",
    "GUITARE",
    "MUSIQUE",
    "SOLISTE",
    "TAMBOUR",
    // 8-letter
    "BATTERIE",
    "HARMONIE",
    "PIANISTE",
    // 9-letter
    "CHANTEUSE",
    "HARMONICA",
    "ORCHESTRE",
    "SAXOPHONE",
    "SYMPHONIE",
    "TROMPETTE",
    "XYLOPHONE",
  ],
  travel: [
    // 3-letter
    "BUS",
    "VOL",
    // 4-letter
    "AUTO",
    "CAMP",
    "GARE",
    "PORT",
    "QUAI",
    "TAXI",
    "TOUR",
    "VISA",
    // 5-letter
    "AVION",
    "CARTE",
    "FERRY",
    "GUIDE",
    "MOTEL",
    "PISTE",
    "PLAGE",
    "ROUTE",
    "TRAIN",
    // 6-letter
    "BAGAGE",
    "BATEAU",
    "BILLET",
    "CABINE",
    "DOUANE",
    "ESCALE",
    "NAVIRE",
    "SAFARI",
    "VALISE",
    "VISITE",
    "VOYAGE",
    // 7-letter
    "AUTOBUS",
    "AUTOCAR",
    "CAMPING",
    "CHARTER",
    "HORAIRE",
    "NAVETTE",
    // 8-letter
    "DOUANIER",
    "MONUMENT",
    "TERMINAL",
    "TOURISTE",
    "VOYAGEUR",
    // 9-letter
    "AUTOROUTE",
    "EXCURSION",
    "PASSEPORT",
  ],
  space: [
    // 3-letter
    "GAZ",
    // 4-letter
    "CIEL",
    "LUNE",
    "MARS",
    "NASA",
    "OVNI",
    "VIDE",
    // 5-letter
    "ALIEN",
    "ASTRE",
    "PLUTO",
    "RADAR",
    "SONDE",
    "TERRE",
    // 6-letter
    "APOLLO",
    "COSMOS",
    "ORBITE",
    "PLUTON",
    "SOLEIL",
    "URANUS",
    // 7-letter
    "GALAXIE",
    "JUPITER",
    "MERCURE",
    "NEPTUNE",
    "SATURNE",
    "UNIVERS",
    // 9-letter
    "SATELLITE",
  ],
  tools: [
    // 3-letter
    "VIS",
    // 4-letter
    "CLEF",
    "CLOU",
    "LIME",
    "SCIE",
    // 5-letter
    "BURIN",
    "COLLE",
    "CORDE",
    "FORET",
    "GOUGE",
    "HACHE",
    "MEULE",
    "OUTIL",
    "PELLE",
    "PINCE",
    "RABOT",
    "RIVET",
    "SERRE",
    // 6-letter
    "BOULON",
    "CISEAU",
    "COMPAS",
    "LEVIER",
    "NIVEAU",
    // 7-letter
    "FOREUSE",
    "MARTEAU",
    // 8-letter
    "CISAILLE",
    "MEULEUSE",
    "PERCEUSE",
    "PONCEUSE",
    "TENAILLE",
    "VISSEUSE",
    // 9-letter
    "AGRAFEUSE",
    "CHALUMEAU",
    "TOURNEVIS",
  ],
  countries: [
    // 3-letter
    "USA",
    // 4-letter
    "CUBA",
    "INDE",
    "IRAK",
    "IRAN",
    "LAOS",
    "MALI",
    "OMAN",
    "TOGO",
    // 5-letter
    "BENIN",
    "CHILI",
    "CHINE",
    "FIDJI",
    "GABON",
    "GHANA",
    "GRECE",
    "HAITI",
    "JAPON",
    "KENYA",
    "LIBAN",
    "LIBYE",
    "MALTE",
    "MAROC",
    "NEPAL",
    "NIGER",
    "PEROU",
    "QATAR",
    "SUEDE",
    "SYRIE",
    "TCHAD",
    "TONGA",
    "YEMEN",
    // 6-letter
    "BELIZE",
    "BRESIL",
    "BRUNEI",
    "CANADA",
    "CHYPRE",
    "EGYPTE",
    "FRANCE",
    "GUYANE",
    "ISRAEL",
    "ITALIE",
    "KOWEIT",
    "MALAWI",
    "MONACO",
    "PANAMA",
    "RUSSIE",
    "SERBIE",
    "TAIWAN",
    "TUVALU",
    "ZAMBIE",
    // 7-letter
    "ALBANIE",
    "ALGERIE",
    "ANDORRE",
    "ARMENIE",
    "BAHAMAS",
    "BAHREIN",
    "BARBADE",
    "BHOUTAN",
    "BOLIVIE",
    "CROATIE",
    "ESPAGNE",
    "ESTONIE",
    "GEORGIE",
    "GRENADE",
    "HONGRIE",
    "IRLANDE",
    "ISLANDE",
    "LIBERIA",
    "MAURICE",
    "MEXIQUE",
    "MYANMAR",
    "NAMIBIE",
    "NIGERIA",
    "NORVEGE",
    "OUGANDA",
    "POLOGNE",
    "SENEGAL",
    "TUNISIE",
    "TURQUIE",
    "UKRAINE",
    "URUGUAY",
    "VANUATU",
    "VIETNAM",
    // 8-letter
    "AUTRICHE",
    "BELGIQUE",
    "BOTSWANA",
    "BULGARIE",
    "CAMBODGE",
    "CAMEROUN",
    "COLOMBIE",
    "DANEMARK",
    "DJIBOUTI",
    "EQUATEUR",
    "ERYTHREE",
    "ETHIOPIE",
    "FINLANDE",
    "HONDURAS",
    "JAMAIQUE",
    "JORDANIE",
    "KIRIBATI",
    "LETTONIE",
    "LITUANIE",
    "MALAISIE",
    "MALDIVES",
    "MOLDAVIE",
    "MONGOLIE",
    "PAKISTAN",
    "PARAGUAY",
    "PORTUGAL",
    "ROUMANIE",
    "SLOVENIE",
    "SRILANKA",
    "SURINAME",
    "TANZANIE",
    "ZIMBABWE",
    // 9-letter
    "ALLEMAGNE",
    "ARGENTINE",
    "AUSTRALIE",
    "DOMINIQUE",
    "GUATEMALA",
    "INDONESIE",
    "NICARAGUA",
    "SINGAPOUR",
    "SLOVAQUIE",
    "SWAZILAND",
    "THAILANDE",
    "VENEZUELA",
  ],
  vehicles: [
    // 3-letter
    "BUS",
    // 4-letter
    "AUTO",
    "CHAR",
    "JEEP",
    "MOTO",
    "TAXI",
    "TRAM",
    "VELO",
    // 5-letter
    "AVION",
    "BARGE",
    "CANOT",
    "FERRY",
    "FUSEE",
    "KAYAK",
    "METRO",
    "TRAIN",
    "YACHT",
    // 6-letter
    "BALLON",
    "BATEAU",
    "CAMION",
    "NAVIRE",
    "TANKER",
    "VAPEUR",
    // 7-letter
    "AUTOBUS",
    "AUTOCAR",
    "BERLINE",
    "CAROSSE",
    "CHARIOT",
    "CYCLOPE",
    "FOURGON",
    "GONDOLE",
    "NAVETTE",
    "PLANEUR",
    "SCOOTER",
    "TRAMWAY",
    "VOILIER",
    "VOITURE",
    // 8-letter
    "ASTRONEF",
    "CARAVANE",
    "MONORAIL",
    "PAQUEBOT",
    "REMORQUE",
    "TRACTEUR",
    "TRICYCLE",
    // 9-letter
    "AEROPLANE",
    "AMBULANCE",
    "CABRIOLET",
    "CHALUTIER",
    "LIMOUSINE",
    "MONOSPACE",
    "MOTONEIGE",
    "SATELLITE",
  ],
  flowers: [
    // 3-letter
    "LIS",
    // 4-letter
    "IRIS",
    "ROSE",
    // 5-letter
    "ASTER",
    "CALLA",
    "LILAS",
    "PAVOT",
    "VIOLA",
    // 6-letter
    "AZALEE",
    "BLEUET",
    "CROCUS",
    "DAHLIA",
    "JASMIN",
    "MIMOSA",
    "MUGUET",
    "PENSEE",
    "SALVIA",
    "TULIPE",
    "ZINNIA",
    // 7-letter
    "ANEMONE",
    "BEGONIA",
    "BRUYERE",
    "CAMELIA",
    "CHARDON",
    "FREESIA",
    "FUCHSIA",
    "GERBERA",
    "GLAIEUL",
    "LAVANDE",
    "OEILLET",
    "PETUNIA",
    "PIVOINE",
    // 8-letter
    "CAMELLIA",
    "CYCLAMEN",
    "DIGITALE",
    "GARDENIA",
    "GERANIUM",
    "HIBISCUS",
    "JACINTHE",
    "MAGNOLIA",
    "MYOSOTIS",
    "NARCISSE",
    "ORCHIDEE",
    "VIOLETTE",
    // 9-letter
    "AMARYLLIS",
    "CLEMATITE",
    "HORTENSIA",
    "JONQUILLE",
    "PRIMEVERE",
    "RENONCULE",
    "TOURNESOL",
  ],
  desserts: [
    // 3-letter
    "BUN",
    // 4-letter
    "BABA",
    "CAKE",
    "FLAN",
    // 5-letter
    "BOMBE",
    "CREME",
    "CREPE",
    "GELEE",
    "GLACE",
    "SUCRE",
    "TARTE",
    "TORTE",
    // 6-letter
    "BONBON",
    "CORNET",
    "COULIS",
    "ECLAIR",
    "GATEAU",
    "GAUFRE",
    "MOUSSE",
    "MUFFIN",
    "NOUGAT",
    "SORBET",
    "TRUFFE",
    "YAOURT",
    // 7-letter
    "BEIGNET",
    "BISCUIT",
    "BRIOCHE",
    "BROWNIE",
    "CARAMEL",
    "COMPOTE",
    "FONDANT",
    "GALETTE",
    "MACARON",
    "PALMIER",
    "PARFAIT",
    "PRALINE",
    "PUDDING",
    "SOUFFLE",
    // 8-letter
    "BAVAROIS",
    "BISCOTTE",
    "CHAUSSON",
    "CROQUANT",
    "ENTREMET",
    "MERINGUE",
    "TIRAMISU",
    // 9-letter
    "CHANTILLY",
    "CHARLOTTE",
    "CLAFOUTIS",
    "CROUSTADE",
    "FINANCIER",
    "FRAMBOISE",
    "MADELEINE",
  ],
  jobs: [
    // 3-letter
    "ROI",
    // 4-letter
    "CHEF",
    "JUGE",
    // 5-letter
    "AGENT",
    "GUIDE",
    // 6-letter
    "ACTEUR",
    "AUTEUR",
    "AVOCAT",
    "PILOTE",
    "SOLDAT",
    // 7-letter
    "ARTISAN",
    "ARTISTE",
    "ATHLETE",
    "BARBIER",
    "BOUCHER",
    "DANSEUR",
    "DOCTEUR",
    "EDITEUR",
    "FACTEUR",
    "FERMIER",
    "GARDIEN",
    "MEDECIN",
    "NOTAIRE",
    "PEINTRE",
    "POMPIER",
    "SERVEUR",
    "VENDEUR",
    // 8-letter
    "ANALYSTE",
    "BANQUIER",
    "CAISSIER",
    "CHANTEUR",
    "COIFFEUR",
    "DENTISTE",
    "GEOLOGUE",
    "LIBRAIRE",
    "MUSICIEN",
    "PLOMBIER",
    "POLICIER",
    "TAILLEUR",
    // 9-letter
    "BIJOUTIER",
    "BOULANGER",
    "CHAUFFEUR",
    "COMPTABLE",
    "CUISINIER",
    "DETECTIVE",
    "DIRECTEUR",
    "FLEURISTE",
    "INFIRMIER",
    "INGENIEUR",
    "JARDINIER",
    "MENUISIER",
  ],
  furniture: [
    // 3-letter
    "LIT",
    // 4-letter
    "BANC",
    "POUF",
    "SOFA",
    // 5-letter
    "BAHUT",
    "DIVAN",
    "FUTON",
    "LAMPE",
    "SIEGE",
    "TABLE",
    "TAPIS",
    "TRONE",
    // 6-letter
    "BUFFET",
    "BUREAU",
    "CANAPE",
    "CHAISE",
    "COFFRE",
    "MEUBLE",
    "MIROIR",
    "TIROIR",
    // 7-letter
    "ARMOIRE",
    "BERGERE",
    "COMMODE",
    "CONSOLE",
    "COUSSIN",
    "DOSSIER",
    "ETAGERE",
    "MATELAS",
    "OTTOMAN",
    "VITRINE",
    // 8-letter
    "FAUTEUIL",
    "GUERIDON",
    "TABOURET",
    // 9-letter
    "BANQUETTE",
  ],
  drinks: [
    // 3-letter
    "EAU",
    "GIN",
    "JUS",
    "THE",
    "VIN",
    // 4-letter
    "CAFE",
    "COCA",
    "LAIT",
    "MOKA",
    "RHUM",
    "SAKE",
    "SODA",
    // 5-letter
    "BIERE",
    "CACAO",
    "CHAUD",
    "CIDRE",
    "FRUIT",
    "GLACE",
    "PORTO",
    "PUNCH",
    "SIROP",
    "VODKA",
    // 6-letter
    "ALCOOL",
    "BRANDY",
    "COGNAC",
    "EGGNOG",
    "FRAPPE",
    "MOJITO",
    "NECTAR",
    "SHERRY",
    "TISANE",
    "WHISKY",
    // 7-letter
    "BOISSON",
    "LIQUEUR",
    "MARTINI",
    "SANGRIA",
    "TEQUILA",
    // 8-letter
    "APERITIF",
    "BORDEAUX",
    "BURGUNDY",
    "CHOCOLAT",
    "COCKTAIL",
    "DAIQUIRI",
    "DIGESTIF",
    "ESPRESSO",
    "INFUSION",
    "LIMONADE",
    "SMOOTHIE",
    // 9-letter
    "CHAMPAGNE",
    "GRENADINE",
    "MARGARITA",
    "MILKSHAKE",
    "ORANGEADE",
  ],
  gems: [
    // 4-letter
    "JADE",
    "ONYX",
    // 5-letter
    "AGATE",
    "AMBRE",
    "BERYL",
    "JASPE",
    "NACRE",
    "OPALE",
    "PERLE",
    "RUBIS",
    // 6-letter
    "CORAIL",
    "GRENAT",
    "PIERRE",
    "QUARTZ",
    "SAPHIR",
    "TOPAZE",
    "ZIRCON",
    // 7-letter
    "CITRINE",
    "CRISTAL",
    "DIAMANT",
    "MINERAL",
    "PERIDOT",
    // 8-letter
    "CABOCHON",
    "EMERAUDE",
    "HEMATITE",
    "SPINELLE",
    // 9-letter
    "AMETHYSTE",
    "MALACHITE",
    "TANZANITE",
    "TURQUOISE",
  ],
  dance: [
    // 3-letter
    "BAL",
    "HIP",
    // 4-letter
    "BALL",
    "FETE",
    "GALA",
    "HULA",
    "JAZZ",
    "JIVE",
    "STEP",
    // 5-letter
    "CONGA",
    "DANSE",
    "DISCO",
    "GIGUE",
    "MAMBO",
    "POLKA",
    "RUMBA",
    "SALSA",
    "SAMBA",
    "SWING",
    "TANGO",
    "TWIST",
    "VALSE",
    // 6-letter
    "BALLET",
    "BOLERO",
    "CANCAN",
    "CHACHA",
    "CUMBIA",
    "MENUET",
    "PAVANE",
    "SOIREE",
    // 7-letter
    "BACHATA",
    "FOXTROT",
    "GAVOTTE",
    "MAZURKA",
    "MILONGA",
    "SIRTAKI",
    // 8-letter
    "CAPOEIRA",
    "COTILLON",
    "FLAMENCO",
    "MERENGUE",
    // 9-letter
    "ARABESQUE",
    "JITTERBUG",
    "PIROUETTE",
    "POLONAISE",
    "QUADRILLE",
    "REGGAETON",
  ],
  trees: [
    // 3-letter
    "PIN",
    // 4-letter
    "AUNE",
    "BUIS",
    "ORME",
    // 5-letter
    "AULNE",
    "CEDRE",
    "CHENE",
    "EBENE",
    "FRENE",
    "HETRE",
    "NOYER",
    "SAPIN",
    "SAULE",
    // 6-letter
    "ACACIA",
    "BAMBOU",
    "CYPRES",
    "ERABLE",
    "MURIER",
    // 7-letter
    "BOULEAU",
    "FIGUIER",
    "LAURIER",
    "OLIVIER",
    "ORANGER",
    "PALMIER",
    "PLATANE",
    "POIRIER",
    "POMMIER",
    "SEQUOIA",
    "TILLEUL",
    // 8-letter
    "AMANDIER",
    "CERISIER",
    "MAGNOLIA",
    "PEUPLIER",
    "SYCOMORE",
    // 9-letter
    "JACARANDA",
  ],
  reptiles: [
    // 3-letter
    "BOA",
    // 5-letter
    "AGAME",
    "ANOLE",
    "COBRA",
    "GECKO",
    "MAMBA",
    "ORVET",
    "VARAN",
    // 6-letter
    "CAIMAN",
    "DRAGON",
    "IGUANE",
    "KOMODO",
    "LEZARD",
    "PYTHON",
    "TORTUE",
    "TRITON",
    "VIPERE",
    // 7-letter
    "BASILIC",
    "MONITOR",
    "SERPENT",
    // 8-letter
    "ANACONDA",
    "CAMELEON",
    // 9-letter
    "ALLIGATOR",
    "COULEUVRE",
    "CROCODILE",
    "DINOSAURE",
  ],
  seasons: [
    // 3-letter
    "ETE",
    "GEL",
    // 4-letter
    "AOUT",
    "BEAU",
    "JUIN",
    "MARS",
    "NOEL",
    "VENT",
    "VERT",
    // 5-letter
    "ARBRE",
    "AVRIL",
    "BRISE",
    "CHAUD",
    "FLEUR",
    "FRAIS",
    "FROID",
    "GIVRE",
    "HIVER",
    "NEIGE",
    "ORAGE",
    "PLAGE",
    "PLUIE",
    // 6-letter
    "ANNUEL",
    "BRUINE",
    "CLIMAT",
    "SAISON",
    "SOLEIL",
    // 7-letter
    "AUTOMNE",
    "CHALEUR",
    "FEUILLE",
    "FEUILLU",
    "JUILLET",
    "MOISSON",
    "NEIGEUX",
    // 8-letter
    "AUTOMNAL",
    "BOURGEON",
    "CANICULE",
    "CYCLIQUE",
    "HIVERNAL",
    "PLUVIEUX",
    "SOLSTICE",
    // 9-letter
    "FEUILLAGE",
    "FLORAISON",
    "PRINTEMPS",
  ],
  cinema: [
    // 3-letter
    "JEU",
    // 4-letter
    "ACTE",
    "CLIP",
    "DIVA",
    "FILM",
    "GALA",
    "PLAN",
    "STAR",
    "TOUR",
    // 5-letter
    "BANDE",
    "CADRE",
    "CONTE",
    "COURT",
    "DRAME",
    "EFFET",
    "FINAL",
    "GENRE",
    "IMAGE",
    "OSCAR",
    "PAUSE",
    "PRISE",
    "SUITE",
    "TRAME",
    // 6-letter
    "ACTEUR",
    "BOBINE",
    "CAMERA",
    "EFFETS",
    "STUDIO",
    // 7-letter
    "ACTRICE",
    "AFFICHE",
    "CADRAGE",
    "CASTEUR",
    "COUPURE",
    "FICTION",
    "MONTAGE",
    "PLATEAU",
    "PREMIER",
    // 8-letter
    "AUDITION",
    "CRITIQUE",
    "DIALOGUE",
    "DOUBLAGE",
    "FESTIVAL",
    "SCENARIO",
    "SUSPENSE",
    "THRILLER",
    // 9-letter
    "ANIMATION",
    "FANTAISIE",
    "PELLICULE",
  ],
  farm: [
    // 3-letter
    "BLE",
    "COQ",
    "OIE",
    "PRE",
    // 4-letter
    "ANES",
    "BETE",
    "BOUC",
    "FOIN",
    "HAIE",
    "LAIT",
    "OEUF",
    "OIES",
    "ORGE",
    "OVIN",
    "PORC",
    "SILO",
    "VEAU",
    // 5-letter
    "BOVIN",
    "COCON",
    "COLZA",
    "FERME",
    "LAINE",
    "MEULE",
    "POULE",
    "VACHE",
    // 6-letter
    "AGNEAU",
    "AVOINE",
    "CANARD",
    "CHEVAL",
    "COCHON",
    "GRANGE",
    "LABOUR",
    "MOUTON",
    "PAILLE",
    "POULET",
    // 7-letter
    "CHARRUE",
    "ENGRAIS",
    "FERMIER",
    "MOISSON",
    "POUSSIN",
    "PRAIRIE",
    "SEMENCE",
    // 8-letter
    "AGRICOLE",
    "BERGERIE",
    "FOURRAGE",
    "LAITERIE",
    "SEMAILLE",
    "TRACTEUR",
  ],
  toys: [
    // 3-letter
    "JEU",
    // 4-letter
    "AUTO",
    "CUBE",
    "DOLL",
    "LEGO",
    "LUGE",
    "OURS",
    "PION",
    "YOYO",
    // 5-letter
    "AVION",
    "BALLE",
    "BOITE",
    "CLOWN",
    "CORDE",
    "FUSEE",
    "JOUET",
    "LIVRE",
    "PATIN",
    "ROBOT",
    "SABLE",
    "TRAIN",
    // 6-letter
    "BALLON",
    "BARBIE",
    "BULLES",
    "CABANE",
    "CARTES",
    "CRAYON",
    "DOMINO",
    "MOBILE",
    "MODELE",
    "OURSON",
    "POUPEE",
    "PUZZLE",
    "TOUPIE",
    // 7-letter
    "ARDOISE",
    "CIRCUIT",
    "CONSOLE",
    "DINETTE",
    "MARELLE",
    "PELUCHE",
    "SAUTEUR",
    "VOITURE",
    // 8-letter
    "CARILLON",
    "FIGURINE",
    "TOBOGGAN",
  ],
  spices: [
    // 3-letter
    "AIL",
    "SEL",
    // 4-letter
    "ANIS",
    "CLOU",
    "MIEL",
    "NOIX",
    "THYM",
    // 5-letter
    "ANETH",
    "AROME",
    "CUMIN",
    "CURRY",
    "SAUCE",
    "SAUGE",
    // 6-letter
    "MENTHE",
    "ORIGAN",
    "PERSIL",
    "PIMENT",
    "POIVRE",
    "SAFRAN",
    // 7-letter
    "AROMATE",
    "BASILIC",
    "CURCUMA",
    "FENOUIL",
    "LAURIER",
    "MUSCADE",
    "PAPRIKA",
    "ROMARIN",
    "VANILLE",
    // 8-letter
    "CANNELLE",
    "CERFEUIL",
    "ESTRAGON",
    // 9-letter
    "CARDAMOME",
    "CORIANDRE",
    "GINGEMBRE",
  ],
  metals: [
    // 3-letter
    "FER",
    // 4-letter
    "INOX",
    "ZINC",
    // 5-letter
    "ACIER",
    "ETAIN",
    "FONTE",
    "METAL",
    "PLOMB",
    // 6-letter
    "ARGENT",
    "BARIUM",
    "BRONZE",
    "CHROME",
    "COBALT",
    "CUIVRE",
    "LAITON",
    "LINGOT",
    "NICKEL",
    "RADIUM",
    "SODIUM",
    "TITANE",
    // 7-letter
    "ALLIAGE",
    "CALCIUM",
    "LITHIUM",
    "MERCURE",
    "PLATINE",
    "SOUDURE",
    "URANIUM",
    "WOLFRAM",
    // 8-letter
    "FONDERIE",
    "MINERAIS",
    // 9-letter
    "ALUMINIUM",
    "FERRAILLE",
    "MAGNESIUM",
    "MANGANESE",
    "OXYDATION",
    "POTASSIUM",
  ],
  accessories: [
    // 3-letter
    "PIN",
    "SAC",
    // 4-letter
    "GANT",
    // 5-letter
    "BADGE",
    "BAGUE",
    "BIJOU",
    "PERLE",
    // 6-letter
    "BONNET",
    "BOUCLE",
    "BOUTON",
    "BROCHE",
    "MONTRE",
    // 7-letter
    "BANDEAU",
    "COLLIER",
    "CRAVATE",
    "FOULARD",
    "SACOCHE",
    // 8-letter
    "ALLIANCE",
    "AMULETTE",
    "BRACELET",
    "CEINTURE",
    "LUNETTES",
    "POCHETTE",
    // 9-letter
    "CASQUETTE",
    "MANCHETTE",
    "PENDENTIF",
  ],
  shapes: [
    // 3-letter
    "ARC",
    // 4-letter
    "CUBE",
    "ONDE",
    "PLAN",
    // 5-letter
    "ANGLE",
    "FORME",
    "LIGNE",
    "OVALE",
    "POINT",
    "RAYON",
    "TRAIT",
    // 6-letter
    "CERCLE",
    "COURBE",
    "DISQUE",
    "DROITE",
    "FIGURE",
    "ORBITE",
    "PRISME",
    "RHOMBE",
    // 7-letter
    "CONTOUR",
    "ELLIPSE",
    "LOSANGE",
    "SEGMENT",
    "SPIRALE",
    // 8-letter
    "CYLINDRE",
    "HEXAGONE",
    "OCTOGONE",
    "POLYGONE",
    "PYRAMIDE",
    "TRIANGLE",
    // 9-letter
    "DIAGONALE",
    "HEPTAGONE",
    "PENTAGONE",
    "RECTANGLE",
  ],
  feelings: [
    // 3-letter
    "FOI",
    // 4-letter
    "JOIE",
    "PAIX",
    "PEUR",
    "RAGE",
    "RIRE",
    // 5-letter
    "AMOUR",
    "CALME",
    "DOUTE",
    "ENNUI",
    "ENVIE",
    "HAINE",
    "HONTE",
    "SOUCI",
    // 6-letter
    "COLERE",
    "EFFROI",
    "ESPOIR",
    "FUREUR",
    "HUMEUR",
    "REGRET",
    // 7-letter
    "BONHEUR",
    "CHAGRIN",
    "COURAGE",
    "CRAINTE",
    "DOULEUR",
    "MALAISE",
    "PANIQUE",
    "PASSION",
    "PLAISIR",
    "RESPECT",
    "TERREUR",
    // 8-letter
    "ANGOISSE",
    "EMPATHIE",
    "EUPHORIE",
    "JALOUSIE",
    "PATIENCE",
    "SOLITUDE",
    "SURPRISE",
    // 9-letter
    "AFFECTION",
    "CONFIANCE",
    "GRATITUDE",
    "NOSTALGIE",
    "OPTIMISME",
    "SYMPATHIE",
    "TENDRESSE",
    "TRISTESSE",
  ],
  water: [
    // 3-letter
    "EAU",
    "LAC",
    "MER",
    // 4-letter
    "BAIE",
    "BAIN",
    "FLUX",
    "MARE",
    "ONDE",
    "PORT",
    "QUAI",
    "RIVE",
    // 5-letter
    "BRUME",
    "CANAL",
    "CHUTE",
    "DELTA",
    "DIGUE",
    "GIVRE",
    "GLACE",
    "NAPPE",
    "NEIGE",
    "PLAGE",
    "PLUIE",
    "VAGUE",
    // 6-letter
    "AVERSE",
    "FLEUVE",
    "GOUTTE",
    "HUMIDE",
    "LAGUNE",
    "MARAIS",
    "RAPIDE",
    "SOURCE",
    "VAPEUR",
    // 7-letter
    "CASCADE",
    "CITERNE",
    "COURANT",
    "GLACIER",
    "PISCINE",
    "TORRENT",
    // 8-letter
    "ESTUAIRE",
    "FONTAINE",
    "MARITIME",
    "RUISSEAU",
    // 9-letter
    "AQUATIQUE",
    "CATARACTE",
  ],
  mountains: [
    // 3-letter
    "ALP",
    "COL",
    "PIC",
    "ROC",
    // 4-letter
    "ALPE",
    "CIME",
    "MONT",
    // 5-letter
    "ALPIN",
    "BRUME",
    "COMBE",
    "NEIGE",
    "PAROI",
    "PENTE",
    "RAVIN",
    "ROCHE",
    // 6-letter
    "CANYON",
    "CHALET",
    "GRANIT",
    "GROTTE",
    "MASSIF",
    "PIERRE",
    "RAVINE",
    "REFUGE",
    "ROCHER",
    "SOMMET",
    "VALLEE",
    // 7-letter
    "ALPAGES",
    "CASCADE",
    "CAVERNE",
    "COLLINE",
    "FALAISE",
    "GLACIER",
    "GOUFFRE",
    "MORAINE",
    "NEIGEUX",
    "PLATEAU",
    "ROCHEUX",
    "SENTIER",
    "TORRENT",
    "VERSANT",
    // 8-letter
    "ALTITUDE",
    "ESCALADE",
    "GRIMPEUR",
    "MONTAGNE",
    "PANORAMA",
    // 9-letter
    "ALPINISME",
    "AVALANCHE",
  ],
  seafood: [
    // 3-letter
    "BAR",
    "MER",
    // 4-letter
    "LIEU",
    "PLIE",
    "RAIE",
    "SOLE",
    "THON",
    // 5-letter
    "BULOT",
    "COLIN",
    "COQUE",
    "CRABE",
    "FILET",
    "MERLU",
    "MOULE",
    // 6-letter
    "CAVIAR",
    "GAMBAS",
    "HARENG",
    "HOMARD",
    "PERCHE",
    "POULPE",
    "SAUMON",
    "SEICHE",
    "TRUITE",
    // 7-letter
    "ANCHOIS",
    "CALAMAR",
    "DAURADE",
    "SARDINE",
    // 8-letter
    "COQUILLE",
    "CREVETTE",
    "PALOURDE",
    // 9-letter
    "BIGORNEAU",
    "CABILLAUD",
    "LANGOUSTE",
    "MAQUEREAU",
  ],
  camping: [
    // 3-letter
    "FEU",
    "LAC",
    "SAC",
    // 4-letter
    "ABRI",
    "BOIS",
    "CAMP",
    "FEUX",
    "LUNE",
    "NUIT",
    "OURS",
    "SEAU",
    // 5-letter
    "ABRIS",
    "ARBRE",
    "CARTE",
    "CORDE",
    "DUVET",
    "HAMAC",
    "KAYAK",
    "LAMPE",
    "PIQUE",
    "PLEIN",
    "SABLE",
    "TENTE",
    // 6-letter
    "BRAISE",
    "CABANE",
    "CHALET",
    "FLAMME",
    "GOURDE",
    "MARCHE",
    "NATURE",
    "REFUGE",
    "SURVIE",
    "TORCHE",
    // 7-letter
    "BIVOUAC",
    "CAMPING",
    "FEUILLE",
    "MATELAS",
    "PAYSAGE",
    "SENTIER",
    // 8-letter
    "AVENTURE",
    "BOUSSOLE",
    "COUCHAGE",
    "EXPLORER",
    "LANTERNE",
    "PLEINAIR",
    // 9-letter
    "BRINDILLE",
    "FEUILLAGE",
    "MOUSTIQUE",
  ],
  circus: [
    // 3-letter
    "ART",
    // 4-letter
    "CAGE",
    "JEUX",
    "LION",
    "RIRE",
    "SAUT",
    "TOUR",
    // 5-letter
    "BALLE",
    "CLOWN",
    "FOULE",
    "MAGIE",
    "PISTE",
    "TIGRE",
    // 6-letter
    "DOMPTE",
    "FAUVES",
    "PUBLIC",
    // 7-letter
    "ARTISTE",
    "CERCEAU",
    // 8-letter
    "ACROBATE",
    "DOMPTEUR",
    "JONGLEUR",
    // 9-letter
    "ACROBATIE",
    "CHAPITEAU",
    "FUNAMBULE",
    "SPECTACLE",
  ],
  pirates: [
    // 3-letter
    "MER",
    "RUM",
    // 4-letter
    "LOOT",
    "RAME",
    // 5-letter
    "ANCRE",
    "BUTIN",
    "CANON",
    "DAGUE",
    "MARIN",
    "PROIE",
    "SABRE",
    "VOILE",
    // 6-letter
    "BATEAU",
    "COFFRE",
    "FLOTTE",
    "GALION",
    "MOUSSE",
    "NAVIRE",
    "PIRATE",
    // 7-letter
    "BANDEAU",
    "DRAPEAU",
    "PILLAGE",
    // 8-letter
    "ABORDAGE",
    "AVENTURE",
    "CORSAIRE",
    "PAVILLON",
    // 9-letter
    "BOUCANIER",
    "CAPITAINE",
    "MUTINERIE",
    "PIRATERIE",
    "SQUELETTE",
  ],
  castle: [
    // 3-letter
    "DUC",
    "ROI",
    // 4-letter
    "COUR",
    "MAGE",
    "PONT",
    "TOUR",
    // 5-letter
    "ARMES",
    "BARON",
    "DOUVE",
    "GARDE",
    "LANCE",
    "NOBLE",
    "PORTE",
    "REINE",
    "SALLE",
    "SERFS",
    // 6-letter
    "ARMURE",
    "ASSAUT",
    "DONJON",
    "DRAGON",
    "FESTIN",
    "PALAIS",
    "PRINCE",
    "VASSAL",
    // 7-letter
    "BANQUET",
    "BOUFFON",
    "REMPART",
    "ROYAUME",
    "TOURNOI",
    // 8-letter
    "ALCHIMIE",
    "BATAILLE",
    "COURONNE",
    "CROISADE",
    "SEIGNEUR",
    // 9-letter
    "CATAPULTE",
    "CHEVALIER",
    "CITADELLE",
    "PRINCESSE",
  ],
  jungle: [
    // 3-letter
    "BOA",
    "FEU",
    // 4-letter
    "BOUE",
    "VERT",
    // 5-letter
    "ARBRE",
    "COBRA",
    "DENSE",
    "FAUNE",
    "FLORE",
    "LIANE",
    "PLUIE",
    "SINGE",
    "TIGRE",
    // 6-letter
    "BAMBOU",
    "HUMIDE",
    "IGUANE",
    "JAGUAR",
    "PYTHON",
    "RACINE",
    "TOUCAN",
    "VAPEUR",
    // 7-letter
    "AMAZONE",
    "CHALEUR",
    "FEUILLE",
    "GORILLE",
    "HABITAT",
    "INSECTE",
    "PALMIER",
    "PIRANHA",
    "SERPENT",
    // 8-letter
    "ANACONDA",
    "EXOTIQUE",
    "TROPICAL",
    // 9-letter
    "CROCODILE",
    "FEUILLAGE",
    "MOUSTIQUE",
    "PERROQUET",
  ],
  desert: [
    // 3-letter
    "ERG",
    "SEC",
    "SOL",
    // 4-letter
    "DUNE",
    "MESA",
    "SOIF",
    "VENT",
    // 5-letter
    "ARIDE",
    "EPINE",
    "OASIS",
    "PALME",
    "PISTE",
    "ROCHE",
    "SABLE",
    // 6-letter
    "CACTUS",
    "CANYON",
    "COYOTE",
    "LEZARD",
    "MIRAGE",
    "NOMADE",
    "RAVINE",
    "SAHARA",
    "SOLEIL",
    "STEPPE",
    // 7-letter
    "ARIDITE",
    "BEDOUIN",
    "CHALEUR",
    "CHAMEAU",
    "HORIZON",
    "SERPENT",
    "TORRIDE",
    "VAUTOUR",
    // 8-letter
    "CANICULE",
    "CARAVANE",
    "SCORPION",
  ],
  arctic: [
    // 3-letter
    "GEL",
    "OUR",
    // 4-letter
    "NORD",
    "ORCA",
    "OURS",
    // 5-letter
    "FROID",
    "GIVRE",
    "GLACE",
    "HUSKY",
    "IGLOO",
    "INUIT",
    "KAYAK",
    "MORSE",
    "NEIGE",
    "RENNE",
    // 6-letter
    "AURORE",
    "NARVAL",
    "PHOQUE",
    "SURVIE",
    // 7-letter
    "CARIBOU",
    "GLACIER",
    "ICEBERG",
    "POLAIRE",
    "TOUNDRA",
    // 8-letter
    "ARCTIQUE",
    "BANQUISE",
    "BLIZZARD",
    "PINGOUIN",
    // 9-letter
    "AVALANCHE",
    "MIGRATION",
  ],
  carnival: [
    // 3-letter
    "BAL",
    "FOU",
    "ROI",
    // 4-letter
    "BALE",
    "CHAR",
    "FETE",
    "JOIE",
    // 5-letter
    "BANDA",
    "CORSO",
    "DANSE",
    "GIGUE",
    "REINE",
    "SAMBA",
    // 6-letter
    "DEFILE",
    "LIESSE",
    "MASQUE",
    "PARADE",
    "PLUMES",
    "RYTHME",
    // 7-letter
    "BOUFFON",
    "COSTUME",
    "FANFARE",
    "MUSIQUE",
    "TAMBOUR",
    // 8-letter
    "CARNAVAL",
    "COTILLON",
    "DANSEUSE",
    "FESTIVAL",
    "FOLKLORE",
    "MUSICIEN",
    // 9-letter
    "ALEGRESSE",
    "CONFETTIS",
    "SERPENTIN",
    "SPECTACLE",
    "TAMBOURIN",
  ],
};
