import type { ThemeId } from "../../utils/themes";

export const pt: Record<ThemeId, string[]> = {
  animals: [
    // 3-letter
    "AVE",
    "BOI",
    "REI",
    // 4-letter
    "ATUM",
    "FOCA",
    "GALO",
    "GATO",
    "LEAO",
    "LOBO",
    "PATO",
    "PERU",
    "RATO",
    "SAPO",
    "URSO",
    "VACA",
    // 5-letter
    "AGUIA",
    "ARARA",
    "BURRO",
    "CABRA",
    "CERVO",
    "COBRA",
    "CORVO",
    "GANSO",
    "KOALA",
    "LHAMA",
    "MORSA",
    "PAVAO",
    "PEIXE",
    "PORCO",
    "TIGRE",
    "TOURO",
    "ZEBRA",
    // 6-letter
    "ARANHA",
    "BALEIA",
    "CAMELO",
    "CASTOR",
    "CAVALO",
    "COELHO",
    "CORUJA",
    "FALCAO",
    "GIRAFA",
    "GORILA",
    "IGUANA",
    "JAGUAR",
    "JAVALI",
    "LONTRA",
    "MACACO",
    "OVELHA",
    "RAPOSA",
    "TUCANO",
    // 7-letter
    "CANGURU",
    "CIGARRA",
    "GALINHA",
    "MORCEGO",
    "PANTERA",
    "PINGUIM",
    // 8-letter
    "ANTILOPE",
    "CAMALEAO",
    "ELEFANTE",
    "FLAMINGO",
    "GOLFINHO",
    "LEOPARDO",
    "PAPAGAIO",
    // 9-letter
    "BORBOLETA",
    "CROCODILO",
    "TARTARUGA",
  ],
  food: [
    // 3-letter
    "CHA",
    "MEL",
    "OVO",
    "PAO",
    "SAL",
    "UVA",
    // 4-letter
    "ALHO",
    "BIFE",
    "BOLO",
    "CAFE",
    "MACA",
    "PERA",
    "SOPA",
    "TACO",
    "UVAS",
    // 5-letter
    "ARROZ",
    "BACON",
    "CARNE",
    "COUVE",
    "CREME",
    "LEITE",
    "LIMAO",
    "MANGA",
    "MELAO",
    "MILHO",
    "MOLHO",
    "NATAS",
    "NOZES",
    "PEIXE",
    "PIZZA",
    "TORTA",
    // 6-letter
    "ALFACE",
    "AMEIXA",
    "BANANA",
    "BATATA",
    "CEBOLA",
    "CEREJA",
    "FEIJAO",
    "FRANGO",
    "GOIABA",
    "PAPAIA",
    "QUEIJO",
    "SALADA",
    "TOMATE",
    // 7-letter
    "ABACATE",
    "ABACAXI",
    "ASPARGO",
    "CAMARAO",
    "CENOURA",
    "LARANJA",
    "MORANGO",
    "PALMITO",
    "PESSEGO",
    "REPOLHO",
    // 8-letter
    "ASPARGOS",
    "BISCOITO",
    "MACARRAO",
    "PIMENTAO",
    // 9-letter
    "ABOBRINHA",
    "CHOCOLATE",
    "ESPINAFRE",
    "SANDUICHE",
  ],
  fruits: [
    // 3-letter
    "UVA",
    // 4-letter
    "COCO",
    "FIGO",
    "KIWI",
    "LIMA",
    "MACA",
    "PERA",
    // 5-letter
    "AMORA",
    "CACAU",
    "CAQUI",
    "LIMAO",
    "MAMAO",
    "MANGA",
    "MELAO",
    // 6-letter
    "AMEIXA",
    "BANANA",
    "CEREJA",
    "GOIABA",
    // 7-letter
    "ABACATE",
    "ABACAXI",
    "ACEROLA",
    "LARANJA",
    "MORANGO",
    "PESSEGO",
    "PITANGA",
    "TORANJA",
    // 8-letter
    "CASTANHA",
    "GRAVIOLA",
    "MARACUJA",
    "MELANCIA",
    "MIRTILOS",
    // 9-letter
    "CARAMBOLA",
    "FRAMBOESA",
    "NECTARINA",
    "TAMARINDO",
    "TANGERINA",
  ],
  colors: [
    // 3-letter
    "COR",
    // 4-letter
    "AZUL",
    "BEGE",
    "JADE",
    "OCRE",
    "OURO",
    "ROSA",
    "ROXO",
    // 5-letter
    "AMBAR",
    "BORDO",
    "CINZA",
    "COBRE",
    "CORAL",
    "CREME",
    "LILAS",
    "OLIVA",
    "PRATA",
    "PRETO",
    "VERDE",
    "VINHO",
    // 6-letter
    "BRANCO",
    "BRONZE",
    "CARMIM",
    "CEREJA",
    "INDIGO",
    "MARFIM",
    "MARROM",
    "PEROLA",
    "SALMAO",
    // 7-letter
    "AMARELO",
    "DOURADO",
    "FUCHSIA",
    "LARANJA",
    "LAVANDA",
    "MAGENTA",
    "PURPURA",
    "VIOLETA",
    // 8-letter
    "BORGONHA",
    "CARAMELO",
    "CARMESIM",
    "CASTANHO",
    "MOSTARDA",
    "TURQUESA",
    "VERMELHO",
    // 9-letter
    "CHAMPANHE",
    "CHOCOLATE",
    "ESMERALDA",
    "TERRACOTA",
  ],
  body: [
    // 3-letter
    "MAO",
    "RIM",
    // 4-letter
    "BOCA",
    "CARA",
    "DEDO",
    "OLHO",
    "OSSO",
    "PELE",
    "UNHA",
    // 5-letter
    "BRACO",
    "DENTE",
    "LABIO",
    "NARIZ",
    "OMBRO",
    "PERNA",
    "PULSO",
    // 6-letter
    "CABECA",
    "CABELO",
    "COLUNA",
    "COSTAS",
    "CRANIO",
    "FIGADO",
    "JOELHO",
    "LINGUA",
    "ORELHA",
    "PULMAO",
    "SANGUE",
    "TENDAO",
    // 7-letter
    "ARTERIA",
    "BARRIGA",
    "CEREBRO",
    "CORACAO",
    "ESOFAGO",
    "MUSCULO",
    "PESCOCO",
    "QUADRIL",
    // 8-letter
    "COTOVELO",
    "ESTOMAGO",
    "GARGANTA",
    "PANCREAS",
    // 9-letter
    "CALCANHAR",
    "CLAVICULA",
    "INTESTINO",
    "TORNOZELO",
  ],
  family: [
    // 3-letter
    "PAI",
    "TIA",
    "TIO",
    // 4-letter
    "IRMA",
    "NETA",
    "NETO",
    "NORA",
    "TIOS",
    // 5-letter
    "CASAL",
    "FILHA",
    "FILHO",
    "GENRO",
    "IRMAO",
    "PAPAI",
    "PRIMA",
    "PRIMO",
    "SOGRA",
    "SOGRO",
    // 6-letter
    "ESPOSA",
    "ESPOSO",
    "GEMEOS",
    "MARIDO",
    "MULHER",
    "PRIMOS",
    // 7-letter
    "BISNETA",
    "BISNETO",
    "CUNHADA",
    "CUNHADO",
    "ENTEADA",
    "ENTEADO",
    "FAMILIA",
    "MADINHA",
    "PARENTE",
    // 8-letter
    "AFILHADA",
    "AFILHADO",
    "MADRASTA",
    "MADRINHA",
    "PADRASTO",
    "PADRINHO",
    "SOBRINHA",
    "SOBRINHO",
    // 9-letter
    "ANCESTRAL",
  ],
  clothing: [
    // 3-letter
    "TOP",
    // 4-letter
    "ANEL",
    "BONE",
    "BOTA",
    "CAPA",
    "LUVA",
    "MEIA",
    "SAIA",
    // 5-letter
    "BLUSA",
    "BOLSA",
    "CALCA",
    "CINTO",
    "CUECA",
    "GORRO",
    "JEANS",
    "LENCO",
    "ROUPA",
    "SHORT",
    "TENIS",
    "TERNO",
    // 6-letter
    "CAMISA",
    "CASACO",
    "CHAPEU",
    "COLETE",
    "PIJAMA",
    "REGATA",
    "SAPATO",
    "SUETER",
    // 7-letter
    "BERMUDA",
    "BIQUINI",
    "CARDIGA",
    "GRAVATA",
    "JAQUETA",
    "MOLETON",
    "VESTIDO",
    // 8-letter
    "AGASALHO",
    "CACHECOL",
    "CALCINHA",
    "CAMISETA",
    "CAMISOLA",
    "CHINELOS",
    "SANDALIA",
  ],
  kitchen: [
    // 3-letter
    "CHA",
    "PIA",
    // 4-letter
    "COPO",
    "FACA",
    "MESA",
    "POTE",
    // 5-letter
    "BACIA",
    "FOGAO",
    "FORNO",
    "GARFO",
    "PRATO",
    // 6-letter
    "COLHER",
    "CONCHA",
    "PANELA",
    "TIGELA",
    "XICARA",
    // 7-letter
    "BANDEJA",
    "PENEIRA",
    "RALADOR",
    // 8-letter
    "CHALEIRA",
    "TALHERES",
    // 9-letter
    "ASSADEIRA",
    "BATEDEIRA",
    "CAFETEIRA",
    "GELADEIRA",
  ],
  school: [
    // 3-letter
    "GIZ",
    "LER",
    // 4-letter
    "AULA",
    "COLA",
    "GOMA",
    "MAPA",
    "NOTA",
    "SALA",
    // 5-letter
    "ALUNO",
    "BANCO",
    "BOLSA",
    "CURSO",
    "DEVER",
    "EXAME",
    "LAPIS",
    "LICAO",
    "LIVRO",
    "LOUSA",
    "PAPEL",
    "PROVA",
    "REGUA",
    "TEXTO",
    "TUTOR",
    // 6-letter
    "CANETA",
    "CLASSE",
    "COLEGA",
    "ESCOLA",
    "ESTOJO",
    "ESTUDO",
    "FISICA",
    "PINCEL",
    "TAREFA",
    // 7-letter
    "ALGEBRA",
    "CADERNO",
    "DIPLOMA",
    "DIRETOR",
    "GINASIO",
    "MOCHILA",
    "QUIMICA",
    "RECREIO",
    // 8-letter
    "BIOLOGIA",
    "CIENCIAS",
    "CORRECAO",
    "EDUCACAO",
    "HISTORIA",
    // 9-letter
    "GEOGRAFIA",
    "PROFESSOR",
  ],
  garden: [
    // 4-letter
    "ALHO",
    "ERVA",
    "FLOR",
    "LAMA",
    "MATO",
    "MUDA",
    "RAIZ",
    "REGA",
    "ROSA",
    "SOLO",
    "VASO",
    // 5-letter
    "ADUBO",
    "BROTO",
    "CACTO",
    "CAULE",
    "CERCA",
    "CRAVO",
    "DALIA",
    "FOLHA",
    "GRAMA",
    "HORTA",
    "LIRIO",
    "TERRA",
    // 6-letter
    "ADUBOS",
    "ARVORE",
    "JARDIM",
    "JASMIM",
    "PLANTA",
    "TRONCO",
    "TULIPA",
    // 7-letter
    "AZALEIA",
    "BEGONIA",
    "LAVANDA",
    "REGADOR",
    "SEMENTE",
    // 8-letter
    "CANTEIRO",
    "GIRASSOL",
    "ORQUIDEA",
    // 9-letter
    "HORTENCIA",
    "MARGARIDA",
  ],
  birds: [
    // 3-letter
    "AVE",
    "EMA",
    // 4-letter
    "EMAS",
    "GALO",
    "GROU",
    "PATO",
    // 5-letter
    "AGUIA",
    "ARARA",
    "CISNE",
    "CORVO",
    "GANSA",
    "PAVAO",
    "POMBA",
    "SABIA",
    "URUBU",
    // 6-letter
    "CONDOR",
    "CORUJA",
    "FALCAO",
    "GAVIAO",
    "PARDAL",
    "TUCANO",
    // 7-letter
    "CANARIO",
    "CARDEAL",
    "CIGARRA",
    "CODORNA",
    "MARRECO",
    "PINGUIM",
    // 8-letter
    "ALBATROZ",
    "FLAMINGO",
    "PAPAGAIO",
    "PELICANO",
    "ROUXINOL",
    // 9-letter
    "ANDORINHA",
    "PERIQUITO",
  ],
  insects: [
    // 5-letter
    "BICHO",
    "BROCA",
    "CUPIM",
    "GRILO",
    "LARVA",
    "MOSCA",
    "PULGA",
    "TRACA",
    "VESPA",
    // 6-letter
    "ABELHA",
    "ARANHA",
    "BARATA",
    "PIOLHO",
    "PULGAO",
    // 7-letter
    "BESOURO",
    "CIGARRA",
    "FORMIGA",
    "LAGARTA",
    // 8-letter
    "CARUNCHO",
    "JOANINHA",
    "LIBELULA",
    "MARIPOSA",
    "MOSQUITO",
    "TATURANA",
    // 9-letter
    "BORBOLETA",
    "CARRAPATO",
    "CENTOPEIA",
    "ESCORPIAO",
    "GAFANHOTO",
    "PERCEVEJO",
  ],
  weather: [
    // 3-letter
    "SOL",
    // 4-letter
    "FRIO",
    "GELO",
    "NEVE",
    "ONDA",
    "RAIO",
    "SECA",
    // 5-letter
    "BRISA",
    "CALOR",
    "CHUVA",
    "CLIMA",
    "GEADA",
    "NUVEM",
    "TEMPO",
    "VENTO",
    // 6-letter
    "TROVAO",
    // 7-letter
    "CICLONE",
    "DILUVIO",
    "GRANIZO",
    "NEBLINA",
    "ORVALHO",
    "TORNADO",
    "UMIDADE",
    // 8-letter
    "ARCOIRIS",
    "NEVOEIRO",
    "PREVISAO",
    "TROVOADA",
    // 9-letter
    "RELAMPAGO",
  ],
  ocean: [
    // 3-letter
    "MAR",
    "OLA",
    // 4-letter
    "AGUA",
    "ALGA",
    "BAIA",
    "BOIA",
    "DUNA",
    "ILHA",
    "ONDA",
    "PIER",
    "REMO",
    "VELA",
    // 5-letter
    "AREIA",
    "BARCO",
    "CORAL",
    "COSTA",
    "FAROL",
    "GOLFO",
    "NAVIO",
    "OSTRA",
    "PEIXE",
    "POLVO",
    "PORTO",
    "PRAIA",
    // 6-letter
    "ANCORA",
    "BALEIA",
    "CONCHA",
    "OCEANO",
    "PEROLA",
    // 7-letter
    "AQUARIO",
    "CAMARAO",
    "ICEBERG",
    "LAGOSTA",
    "LITORAL",
    "TUBARAO",
    "VELEIRO",
    // 8-letter
    "CRUZEIRO",
    "GOLFINHO",
    "MERGULHO",
    "NAUFRAGO",
    // 9-letter
    "SUBMARINO",
  ],
  sports: [
    // 3-letter
    "GOL",
    "SKI",
    // 4-letter
    "ARCO",
    "BOLA",
    "BOXE",
    "JOGO",
    "JUDO",
    "LUTA",
    "NADO",
    "POLO",
    "REDE",
    "REMO",
    "TACO",
    "TIME",
    "TIRO",
    "VELA",
    // 5-letter
    "CAMPO",
    "CANOA",
    "GOLFE",
    "PISTA",
    "RUGBY",
    "SALTO",
    "SKATE",
    "SURFE",
    "TENIS",
    "VOLEI",
    // 6-letter
    "ATLETA",
    "DEFESA",
    "EQUIPE",
    "HOQUEI",
    "KARATE",
    "PLACAR",
    "PONTOS",
    "TROFEU",
    // 7-letter
    "ARBITRO",
    "CAMPEAO",
    "CORRIDA",
    "ESGRIMA",
    "ESTADIO",
    "FUTEBOL",
    "GOLEIRO",
    "MEDALHA",
    "NATACAO",
    "PARTIDA",
    "PILATES",
    // 8-letter
    "BASQUETE",
    "CICLISMO",
    "HANDEBOL",
    "MARATONA",
    // 9-letter
    "BADMINTON",
    "GINASTICA",
    "PATINACAO",
    "TREINADOR",
  ],
  music: [
    // 3-letter
    "POP",
    "RAP",
    "SOM",
    // 4-letter
    "FADO",
    "FUNK",
    "HINO",
    "JAZZ",
    "NOTA",
    "ROCK",
    "SOLO",
    "TUBA",
    // 5-letter
    "ALBUM",
    "BAIXO",
    "BANDA",
    "CANTO",
    "CORAL",
    "DISCO",
    "DUETO",
    "GRUPO",
    "HARPA",
    "LETRA",
    "OPERA",
    "PIANO",
    "RITMO",
    "SAMBA",
    "TENOR",
    "VIOLA",
    "VOCAL",
    // 6-letter
    "ACORDE",
    "BALADA",
    "CANTOR",
    "FLAUTA",
    "MUSICA",
    "REGGAE",
    "TAMBOR",
    "VIOLAO",
    // 7-letter
    "ARTISTA",
    "BATERIA",
    "MAESTRO",
    "MELODIA",
    "REGENTE",
    "TECLADO",
    "VIOLINO",
    // 8-letter
    "ACORDEAO",
    "CONCERTO",
    "GUITARRA",
    "HARMONIA",
    "PIANISTA",
    "SAXOFONE",
    "SINFONIA",
    "TROMBONE",
    "TROMPETE",
    "XILOFONE",
    // 9-letter
    "CLARINETE",
    "ORQUESTRA",
  ],
  travel: [
    // 3-letter
    "VOO",
    // 4-letter
    "GUIA",
    "MALA",
    "MAPA",
    "MOTO",
    "NAVE",
    "ROTA",
    "TAXI",
    "TREM",
    // 5-letter
    "AVIAO",
    "BALSA",
    "BARCO",
    "CARRO",
    "HOTEL",
    "METRO",
    "NAVIO",
    "PORTO",
    "PRAIA",
    "VISTO",
    // 6-letter
    "ADUANA",
    "CAMERA",
    "ESCALA",
    "FERIAS",
    "ONIBUS",
    "SAFARI",
    "VIAGEM",
    // 7-letter
    "BAGAGEM",
    "BILHETE",
    "CHEGADA",
    "DESTINO",
    "MOCHILA",
    "PARTIDA",
    "PASSEIO",
    "RESERVA",
    "ROTEIRO",
    "TURISTA",
    // 8-letter
    "AVENTURA",
    "CRUZEIRO",
    "EMBARQUE",
    "PASSAGEM",
    "TERMINAL",
    // 9-letter
    "AEROPORTO",
    "ALFANDEGA",
    "FRONTEIRA",
    "PEREGRINO",
  ],
  space: [
    // 3-letter
    "CEU",
    "LUA",
    "SOL",
    // 4-letter
    "NASA",
    "OVNI",
    // 5-letter
    "ALIEN",
    "ASTRO",
    "COSMO",
    "MARTE",
    "RADAR",
    "SONDA",
    "TERRA",
    "URANO",
    "VENUS",
    // 6-letter
    "COMETA",
    "CRATER",
    "ESPACO",
    "ORBITA",
    "PLUTAO",
    "QUASAR",
    // 7-letter
    "ECLIPSE",
    "ESTRELA",
    "FOGUETE",
    "GALAXIA",
    "JUPITER",
    "METEORO",
    "NEPTUNO",
    "PLANETA",
    "SATURNO",
    // 8-letter
    "MERCURIO",
    "NEBULOSA",
    "SATELITE",
    "UNIVERSO",
    // 9-letter
    "ASTEROIDE",
    "GRAVIDADE",
    "METEORITO",
  ],
  tools: [
    // 4-letter
    "CABO",
    "FACA",
    "LIMA",
    "LIXA",
    // 5-letter
    "BROCA",
    "CHAVE",
    "PORCA",
    "PREGO",
    "SERRA",
    "TORNO",
    "TRENA",
    // 6-letter
    "ESCADA",
    "ESTOJO",
    "FORMAO",
    "MALETA",
    "PLAINA",
    // 7-letter
    "ALICATE",
    "BANCADA",
    "CADEADO",
    "MACHADO",
    "MARRETA",
    "MARTELO",
    "SERROTE",
    "TESOURA",
    // 8-letter
    "LANTERNA",
    "PARAFUSO",
    "PONTEIRA",
    "SOLDADOR",
    // 9-letter
    "FURADEIRA",
    "LIXADEIRA",
  ],
  countries: [
    // 3-letter
    "EUA",
    "IRA",
    "OMA",
    // 4-letter
    "CUBA",
    "FIJI",
    "GANA",
    "LAOS",
    "MALI",
    "PERU",
    "TOGO",
    // 5-letter
    "BENIM",
    "BUTAO",
    "CATAR",
    "CHADE",
    "CHILE",
    "CHINA",
    "EGITO",
    "GABAO",
    "HAITI",
    "IEMEN",
    "INDIA",
    "JAPAO",
    "LIBIA",
    "MALTA",
    "NEPAL",
    "NIGER",
    "SIRIA",
    "TONGA",
    // 6-letter
    "BELIZE",
    "BRASIL",
    "BRUNEI",
    "CANADA",
    "CHIPRE",
    "FRANCA",
    "GRECIA",
    "GUIANA",
    "IRAQUE",
    "ISRAEL",
    "ITALIA",
    "KUWAIT",
    "LIBANO",
    "MALAWI",
    "MEXICO",
    "MONACO",
    "PANAMA",
    "QUENIA",
    "RUSSIA",
    "SERVIA",
    "SUECIA",
    "TAIWAN",
    "TUVALU",
    "UGANDA",
    "VIETNA",
    "ZAMBIA",
    // 7-letter
    "ALBANIA",
    "ANDORRA",
    "ARGELIA",
    "ARMENIA",
    "AUSTRIA",
    "BAHAMAS",
    "BAHREIN",
    "BELGICA",
    "BOLIVIA",
    "CAMBOJA",
    "CROACIA",
    "DJIBUTI",
    "EQUADOR",
    "ESPANHA",
    "ESTONIA",
    "ETIOPIA",
    "GEORGIA",
    "GRANADA",
    "HUNGRIA",
    "IRLANDA",
    "JAMAICA",
    "LETONIA",
    "LIBERIA",
    "MALASIA",
    "MIANMAR",
    "NAMIBIA",
    "NIGERIA",
    "NORUEGA",
    "POLONIA",
    "ROMENIA",
    "SENEGAL",
    "TUNISIA",
    "TURQUIA",
    "UCRANIA",
    "URUGUAI",
    "VANUATU",
    // 8-letter
    "ALEMANHA",
    "BARBADOS",
    "BOTSUANA",
    "BULGARIA",
    "COLOMBIA",
    "DOMINICA",
    "ERITREIA",
    "HONDURAS",
    "ISLANDIA",
    "JORDANIA",
    "KIRIBATI",
    "LITUANIA",
    "MALDIVAS",
    "MARROCOS",
    "MAURICIO",
    "MOLDAVIA",
    "MONGOLIA",
    "PARAGUAI",
    "PORTUGAL",
    "SRILANKA",
    "SURINAME",
    "TANZANIA",
    "ZIMBABUE",
    // 9-letter
    "ARGENTINA",
    "AUSTRALIA",
    "CINGAPURA",
    "DINAMARCA",
    "ESLOVENIA",
    "FINLANDIA",
    "GUATEMALA",
    "INDONESIA",
    "NICARAGUA",
    "PAQUISTAO",
    "TAILANDIA",
    "VENEZUELA",
  ],
  vehicles: [
    // 3-letter
    "JET",
    "VAN",
    // 4-letter
    "BOTE",
    "JEEP",
    "JIPE",
    "KART",
    "MOTO",
    "TAXI",
    "TREM",
    // 5-letter
    "AVIAO",
    "BALSA",
    "BARCO",
    "CANOA",
    "CARRO",
    "METRO",
    "NAVIO",
    "TRENO",
    "TROLE",
    "YACHT",
    // 6-letter
    "CAMIAO",
    "ONIBUS",
    "PATINS",
    "TRATOR",
    // 7-letter
    "CAIAQUE",
    "CARROCA",
    "FOGUETE",
    "GONDOLA",
    "REBOQUE",
    "SCOOTER",
    "TRAILER",
    "VELEIRO",
    // 8-letter
    "BALSEIRA",
    "CAMINHAO",
    "LIMOSINE",
    "TRICICLO",
    // 9-letter
    "BICICLETA",
    "MONOCICLO",
    "MOTORHOME",
    "SUBMARINO",
  ],
  flowers: [
    // 3-letter
    "IVA",
    // 4-letter
    "AMOR",
    "HERA",
    "IRIS",
    "IXIA",
    "LRIO",
    "ROSA",
    // 5-letter
    "ASTER",
    "CACTO",
    "CRAVO",
    "DALIA",
    "LIRIO",
    "LOTUS",
    "MALVA",
    "VIOLA",
    // 6-letter
    "CROCUS",
    "FRESIA",
    "JASMIN",
    "TULIPA",
    // 7-letter
    "ANEMONA",
    "AZALEIA",
    "BEGONIA",
    "CAMELIA",
    "HIBISCO",
    "JACINTO",
    "LAVANDA",
    "NARCISO",
    "PETUNIA",
    "PRIMULA",
    "VERBENA",
    // 8-letter
    "AMARANTO",
    "AMARILIS",
    "CAMELLIA",
    "GARDENIA",
    "GIRASSOL",
    "GLADIOLO",
    "GLICINIA",
    "HORTENIA",
    "MAGNOLIA",
    "ORQUIDEA",
    "PLUMERIA",
  ],
  desserts: [
    // 3-letter
    "BEM",
    "PIE",
    // 4-letter
    "BOLO",
    "FLAN",
    "NATA",
    "TART",
    // 5-letter
    "CREPE",
    "DONUT",
    "MOUSE",
    "PAVLE",
    "PUDIM",
    "TORTA",
    "TRUFA",
    "WAFER",
    // 6-letter
    "CHURRO",
    "COOKIE",
    "ECLAIR",
    "GELADO",
    "GELEIA",
    "MUFFIN",
    "PANQUE",
    "PAOMEL",
    "TORRAO",
    // 7-letter
    "BROWNIE",
    "CANNOLI",
    "CUPCAKE",
    "MACARON",
    "PARFAIT",
    "PAVLOVA",
    "QUINDIM",
    "SORVETE",
    "STRUDEL",
    "SUSPIRO",
    // 8-letter
    "TIRAMISU",
    // 9-letter
    "MILFOLHAS",
    "ROCAMBOLE",
  ],
  jobs: [
    // 4-letter
    "ATOR",
    "CHEF",
    "GUIA",
    "JUIZ",
    // 5-letter
    "TUTOR",
    // 6-letter
    "GARCOM",
    "MEDICO",
    "MODELO",
    "PILOTO",
    "PINTOR",
    // 7-letter
    "GERENTE",
    "PADEIRO",
    // 8-letter
    "ADVOGADO",
    "BARBEIRO",
    "BOMBEIRO",
    "CARTEIRO",
    "CONTADOR",
    "DENTISTA",
    "DESIGNER",
    "ESCRITOR",
    "MECANICO",
    // 9-letter
    "ARQUITETO",
    "CIENTISTA",
    "FOTOGRAFO",
    "MOTORISTA",
    "PROFESSOR",
  ],
  furniture: [
    // 3-letter
    "BAR",
    // 4-letter
    "CAMA",
    "MESA",
    "PUFE",
    "RACK",
    "REDE",
    "SOFA",
    // 5-letter
    "BANCO",
    "COFRE",
    // 6-letter
    "BALCAO",
    "BUFFET",
    "COMODA",
    "CRIADO",
    "GUARDA",
    // 7-letter
    "ARMARIO",
    "BELICHE",
    "CADEIRA",
    "COLCHAO",
    "ESTANTE",
    "ESTRADO",
    // 8-letter
    "APARADOR",
    "BANQUETA",
    "CREDENZA",
    "DESPENSA",
    "GABINETE",
    "POLTRONA",
    "TOUCADOR",
    // 9-letter
    "CABECEIRA",
    "CABIDEIRO",
    "ESCADINHA",
  ],
  drinks: [
    // 3-letter
    "CHA",
    "GIN",
    "RUM",
    // 4-letter
    "AGUA",
    "CAFE",
    "COLA",
    "MATE",
    "SODA",
    "SUCO",
    // 5-letter
    "LEITE",
    "LICOR",
    "SHAKE",
    "TODDY",
    "VINHO",
    "VODKA",
    // 6-letter
    "BATIDA",
    "COGNAC",
    "MOJITO",
    "PONCHE",
    "WHISKY",
    // 7-letter
    "ABACAXI",
    "CAIPIRA",
    "CERVEJA",
    "GUARANA",
    "LARANJA",
    "MARTINI",
    "SANGRIA",
    "TEQUILA",
    // 8-letter
    "DAIQUIRI",
    "ESPRESSO",
    "HORCHATA",
    "LIMONADA",
    "SMOOTHIE",
    // 9-letter
    "MARGARITA",
    "MILKSHAKE",
  ],
  gems: [
    // 4-letter
    "AQUA",
    "JADE",
    "ONIX",
    "RUBI",
    // 5-letter
    "AGATA",
    "AMBAR",
    "CORAL",
    "JASPE",
    "OPALA",
    // 6-letter
    "BERILO",
    "PEROLA",
    "SAFIRA",
    // 7-letter
    "CITRINO",
    "CRISTAL",
    "GRANADA",
    "KUNZITA",
    "QUARTZO",
    "TOPAZIO",
    // 8-letter
    "AMETISTA",
    "AMETRINA",
    "DIAMANTE",
    "ESPINELA",
    "HEMATITA",
    "PERIDOTO",
    "RODONITA",
    "TURQUESA",
    "ZIRCONIA",
    // 9-letter
    "AMAZONITA",
    "ESMERALDA",
    "MALACHITA",
    "MOONSTONE",
    "OBSIDIANA",
    "TANZANITA",
    "TURMALINA",
  ],
  dance: [
    // 3-letter
    "RAP",
    // 4-letter
    "FADO",
    "FUNK",
    "JAZZ",
    "JIVE",
    "POLE",
    // 5-letter
    "BREAK",
    "FORRO",
    "FREVO",
    "MAMBO",
    "POLCA",
    "RUMBA",
    "SALSA",
    "SAMBA",
    "SWING",
    "TANGO",
    "VALSA",
    "ZUMBA",
    // 6-letter
    "BALLET",
    "BOLERO",
    "CUMBIA",
    "MAXIXE",
    // 7-letter
    "BACHATA",
    "BATUQUE",
    "CARIMBO",
    "COUNTRY",
    "LAMBADA",
    "MAZURCA",
    "MINUETO",
    // 8-letter
    "BURLESCO",
    "CAPOEIRA",
    "COTILHAO",
    "FLAMENCO",
    "LINDYHOP",
    "MERENGUE",
    // 9-letter
    "BARCAROLA",
    "CHACARERA",
    "CHARLSTON",
    "PASODOBLE",
    "QUADRILHA",
    "TARANTELA",
  ],
  trees: [
    // 3-letter
    "IPE",
    "NOZ",
    // 4-letter
    "BUXO",
    "FAIA",
    "LIMA",
    "OLMO",
    "TECA",
    // 5-letter
    "ABETO",
    "BAMBU",
    "BORDO",
    "CEDRO",
    "FICUS",
    "MOGNO",
    "PINHO",
    // 6-letter
    "ACACIA",
    "BONSAI",
    "PEROBA",
    // 7-letter
    "AROEIRA",
    "PLATANO",
    "SEQUOIA",
    // 8-letter
    "AVELEIRA",
    "CARVALHO",
    "CIPRESTE",
    "FIGUEIRA",
    "LIMOEIRO",
    "MACIEIRA",
    "MAGNOLIA",
    "NOGUEIRA",
    "OLIVEIRA",
    "PALMEIRA",
    // 9-letter
    "ARAUCARIA",
    "BANANEIRA",
    "CEREJEIRA",
    "EUCALIPTO",
    "JACARANDA",
    "MANGUEIRA",
    "TAMARINDO",
  ],
  reptiles: [
    // 3-letter
    "BOA",
    // 4-letter
    "NAJA",
    "SAPO",
    "TEIU",
    // 5-letter
    "COBRA",
    "CORAL",
    "GECKO",
    "PITON",
    // 6-letter
    "CAIMAN",
    "DRAGAO",
    "IGUANA",
    "JABUTI",
    "JIBOIA",
    "SUCURI",
    "VIBORA",
    // 7-letter
    "CALANGO",
    "CROTALO",
    "LAGARTO",
    "TEIUACU",
    "TUATARA",
    // 8-letter
    "ALIGATOR",
    "ANACONDA",
    "CAMALEAO",
    "CASCAVEL",
    "JARARACA",
    "SERPENTE",
    // 9-letter
    "BASILISCO",
    "CAGUARANA",
    "CROCODILO",
    "JABOTINHA",
    "LAGARTIXA",
    "MORDEGUIA",
    "TARTARUGA",
  ],
  seasons: [
    // 3-letter
    "CEU",
    "MAR",
    "SOL",
    // 4-letter
    "FLOR",
    "FRIO",
    "GELO",
    "NEVE",
    // 5-letter
    "ABRIL",
    "BRISA",
    "CALOR",
    "CHUVA",
    "CLIMA",
    "FOLHA",
    "GEADA",
    "JULHO",
    "JUNHO",
    "MARCO",
    "NUVEM",
    "OTONO",
    "PRAIA",
    "VENTO",
    "VERAO",
    "VERDE",
    // 6-letter
    "AGOSTO",
    "BROTES",
    "GELADO",
    "OUTONO",
    // 7-letter
    "CICLICO",
    "ESTACAO",
    "ESTIVAL",
    "GRANIZO",
    "INVERNO",
    "JANEIRO",
    "MUDANCA",
    "NEBLINA",
    "OUTONAL",
    "OUTUBRO",
    "SAZONAL",
    "SOLEADO",
    // 8-letter
    "ARCOIRIS",
    "COLHEITA",
    "DEZEMBRO",
    "INVERNAL",
    "NATUREZA",
    "NOVEMBRO",
    "SETEMBRO",
    "TEMPORAL",
    "TROPICAL",
    // 9-letter
    "EQUINOCIO",
    "PRIMAVERA",
    "SOLSTICIO",
  ],
  cinema: [
    // 3-letter
    "SET",
    // 4-letter
    "ACAO",
    "ATOR",
    "CENA",
    "DIVA",
    "FAMA",
    "FILM",
    "GALA",
    "MUDO",
    "SALA",
    "STAR",
    "TELA",
    "TOMA",
    // 5-letter
    "ATRIZ",
    "AUDIO",
    "CORTE",
    "CURTA",
    "DRAMA",
    "FILME",
    "FINAL",
    "LONGA",
    "OSCAR",
    "PAPEL",
    "PAUSA",
    "PLANO",
    "SCENA",
    "SERIE",
    "TRAMA",
    "VIDEO",
    // 6-letter
    "BOBINA",
    "CACHET",
    "CAMERA",
    "CARTAZ",
    "CINEMA",
    "EFEITO",
    "ELENCO",
    "ENREDO",
    "FICCAO",
    "GENERO",
    "PIPOCA",
    "SESSAO",
    "TERROR",
    // 7-letter
    "COMEDIA",
    "CREDITO",
    "CRITICA",
    "DIALOGO",
    "DIRETOR",
    "EFEITOS",
    "ESTREIA",
    "ESTRELA",
    "LEGENDA",
    "NOMEADO",
    "ROTEIRO",
    "TRAILER",
    // 8-letter
    "ANIMACAO",
    "CINEASTA",
    "CINEFILO",
    "DUBLAGEM",
    "FANTASIA",
    "FIGURINO",
    "FILMAGEM",
    "MONTAGEM",
    "PRODUTOR",
    "PROJECAO",
    "SUSPENSE",
    // 9-letter
    "SEQUENCIA",
  ],
  farm: [
    // 3-letter
    "AVE",
    "BOI",
    "OVO",
    "SOL",
    // 4-letter
    "BODE",
    "BOLO",
    "ERVA",
    "FENO",
    "GADO",
    "GALO",
    "PATO",
    "PERU",
    "SILO",
    "TORO",
    "VACA",
    // 5-letter
    "ARADO",
    "AVEIA",
    "BURRO",
    "CABRA",
    "CAMPO",
    "CAPIM",
    "CERCA",
    "GANSO",
    "GRAMA",
    "GRANO",
    "HORTA",
    "LHAMA",
    "MILHO",
    "PASTO",
    "PORCA",
    "PORCO",
    "TRIGO",
    // 6-letter
    "ALFAFA",
    "CAVALO",
    "COELHO",
    "CURRAL",
    "OVELHA",
    "POMBAL",
    "TRATOR",
    // 7-letter
    "BEZERRO",
    "CAIEIRA",
    "CELEIRO",
    "CRIACAO",
    "CULTIVO",
    "FAZENDA",
    "GALINHA",
    "IRRIGAR",
    "LAVOURA",
    // 8-letter
    "CAMPONES",
    "COLHEITA",
    "ESTABULO",
    "MAQUINAS",
    "ORDENHAR",
    "PASTAGEM",
    "PECUARIA",
    // 9-letter
    "IRRIGACAO",
    "PLANTACAO",
    "PORQUEIRO",
    "SEMEADURA",
  ],
  toys: [
    // 3-letter
    "ARO",
    "BLO",
    "PIU",
    // 4-letter
    "AUTO",
    "BOLA",
    "CUBO",
    "DADO",
    "JOGO",
    "LEGO",
    "PIAO",
    "PIPA",
    "PUPU",
    "ROBO",
    "TREM",
    "URSO",
    "YOYO",
    // 5-letter
    "BALDE",
    "BARCO",
    "CARRO",
    "CORDA",
    "DARDO",
    "DOMIN",
    "GLOBO",
    "JOGOS",
    "PATIN",
    "ROBOT",
    "TRICO",
    "VIDEO",
    // 6-letter
    "BARBIE",
    "BLOCOS",
    "BONECA",
    "DOMINO",
    "FIGURA",
    "PATINS",
    "PUZZLE",
    "QUEBRA",
    "TOBOGA",
    // 7-letter
    "BALANCO",
    "BOLINHA",
    "CASTELO",
    "COLECAO",
    "CONSOLE",
    "FUTEBOL",
    "PELUCIA",
    "PINTURA",
    // 8-letter
    "BAMBOLEO",
    "CARRINHO",
    "FANTASIA",
    "JOGUINHO",
    "MASSINHA",
    "PATINETE",
    "PLASTICO",
    // 9-letter
    "BICICLETA",
    "MARIONETE",
    "TRAMPOLIM",
    "TRENZINHO",
    "VIDEOGAME",
  ],
  spices: [
    // 3-letter
    "MEL",
    "NOZ",
    "SAL",
    // 4-letter
    "ANIS",
    "DILL",
    "ERVA",
    "NATA",
    "SOJA",
    // 5-letter
    "AROMA",
    "CHILI",
    "CRAVO",
    "CURRY",
    "ENDRO",
    "LOURO",
    "MENTA",
    "SABOR",
    "SALSA",
    // 6-letter
    "CANELA",
    "CHEIRO",
    "SALVIA",
    "URUCUM",
    // 7-letter
    "ACAFRAO",
    "ALECRIM",
    "COENTRO",
    "COMINHO",
    "CURCUMA",
    "OREGANO",
    "PIMENTA",
    "TEMPERO",
    "TOMILHO",
    // 8-letter
    "ALFAVACA",
    "BAUNILHA",
    "ESTRAGAO",
    "GENGIBRE",
    "MOSTARDA",
    // 9-letter
    "CARDAMOMO",
    "CEBOLINHA",
  ],
  metals: [
    // 3-letter
    "ACO",
    // 4-letter
    "LIGA",
    "OURO",
    // 5-letter
    "ARAME",
    "BARIO",
    "COBRE",
    "CROMO",
    "FERRO",
    "LATAO",
    "LITIO",
    "METAL",
    "PRATA",
    "RADIO",
    "SODIO",
    "SOLDA",
    "ZINCO",
    // 6-letter
    "BRONZE",
    "CALCIO",
    "CHUMBO",
    "FORJAR",
    "NIQUEL",
    "URANIO",
    // 7-letter
    "COBALTO",
    "ESTANHO",
    "MINERAL",
    "PLATINA",
    "TITANIO",
    // 8-letter
    "ALUMINIO",
    "FERRAGEM",
    "FUNDICAO",
    "MAGNESIO",
    "MANGANES",
    "MERCURIO",
    "OXIDACAO",
    "POTASSIO",
    // 9-letter
    "SOLDADURA",
  ],
  accessories: [
    // 3-letter
    "ARO",
    "PIN",
    "VEU",
    // 4-letter
    "ANEL",
    "GEMA",
    "JOIA",
    "LACO",
    "LUVA",
    "MALA",
    "PINO",
    "TOCA",
    // 5-letter
    "BOLSA",
    "CINTO",
    "COLAR",
    "COROA",
    "GORRO",
    "LENCO",
    "TIARA",
    // 6-letter
    "ARGOLA",
    "BRINCO",
    "BROCHE",
    "FIVELA",
    "OCULOS",
    "PEROLA",
    // 7-letter
    "AMULETO",
    "DIADEMA",
    "ECHARPE",
    "GRAVATA",
    "MOCHILA",
    "RELOGIO",
    "VISEIRA",
    // 8-letter
    "CACHECOL",
    "CARTEIRA",
    "CORRENTE",
    "PINGENTE",
    "PULSEIRA",
    // 9-letter
    "BRACELETE",
  ],
  shapes: [
    // 3-letter
    "ARC",
    // 4-letter
    "ARCO",
    "CONE",
    "CUBO",
    "GIRO",
    "LADO",
    "ONDA",
    "OVAL",
    "PICO",
    "RAIO",
    // 5-letter
    "CURVA",
    "FORMA",
    "LINHA",
    "PLANO",
    "PONTO",
    "TRACO",
    // 6-letter
    "ANGULO",
    "ARESTA",
    "CONICO",
    "ELIPSE",
    "ESFERA",
    "FIGURA",
    "ORBITA",
    "PRISMA",
    // 7-letter
    "CIRCULO",
    "ESPIRAL",
    "ESTRELA",
    "LOSANGO",
    "VERTICE",
    // 8-letter
    "CILINDRO",
    "CIRCULAR",
    "CONTORNO",
    "DIAGONAL",
    "ESFERICO",
    "HEXAGONO",
    "PARALELO",
    "PIRAMIDE",
    "POLIGONO",
    "QUADRADO",
    "ROMBOIDE",
    "SIMETRIA",
    // 9-letter
    "BISSETRIZ",
    "DECAGONAL",
    "GEOMETRIA",
    "HEXAGONAL",
    "OCTOGONAL",
    "PENTAGONO",
    "PIRAMIDAL",
    "POLIGONAL",
    "RETANGULO",
    "ROMBOIDAL",
  ],
  feelings: [
    // 3-letter
    "IRA",
    "PAZ",
    // 4-letter
    "AMOR",
    "GOZO",
    "LUTO",
    "MEDO",
    "ODIO",
    "PENA",
    "RISO",
    // 5-letter
    "AFETO",
    "ANIMO",
    "CALMA",
    "CIUME",
    "CULPA",
    "DICHA",
    "EXITO",
    "FELIZ",
    "FURIA",
    "GOSTO",
    "HUMOR",
    "MAGOA",
    "RAIVA",
    "SUSTO",
    "TEMOR",
    "VALOR",
    // 6-letter
    "APRECO",
    "DESEJO",
    "DUVIDA",
    "FASTIO",
    "HORROR",
    "INVEJA",
    "PAIXAO",
    "PRAZER",
    "RANCOR",
    // 7-letter
    "ADMIRAR",
    "ALEGRIA",
    "AMIZADE",
    "BONDADE",
    "CARINHO",
    "CORAGEM",
    "EMPATIA",
    "EUFORIA",
    "ORGULHO",
    "SOLIDAO",
    "TERNURA",
    // 8-letter
    "DESANIMO",
    "DESPREZO",
    "GRATIDAO",
    "RESPEITO",
    "SURPRESA",
    "TRISTEZA",
    "VERGONHA",
    // 9-letter
    "ANSIEDADE",
    "ESPERANCA",
    "HUMILDADE",
    "NOSTALGIA",
    "OPTIMISMO",
    "OPTIMISTA",
    "PACIENCIA",
    "TRANQUILO",
  ],
  water: [
    // 3-letter
    "MAR",
    "OLA",
    "RIO",
    // 4-letter
    "AGUA",
    "BAIA",
    "BOTE",
    "CABO",
    "GELO",
    "GOTA",
    "LAGO",
    "NAVE",
    "NEVE",
    "ONDA",
    "ORLA",
    "POCA",
    // 5-letter
    "BALSA",
    "CANAL",
    "CHUVA",
    "COSTA",
    "DELTA",
    "DIQUE",
    "FAROL",
    "FONTE",
    "GOLFO",
    "LAGOA",
    "NADAR",
    "PRAIA",
    "PRESA",
    "ROCHA",
    "VAPOR",
    // 6-letter
    "ARROIO",
    "GEISER",
    "LAGOAS",
    "MANGUE",
    "OCEANO",
    "RIACHO",
    // 7-letter
    "CASCATA",
    "GLACIAR",
    "MARINHA",
    "PANTANO",
    "REPRESA",
    "RIACHOS",
    "RIBEIRA",
    // 8-letter
    "AFLUENTE",
    "AQUATICO",
    "AQUIFERO",
    "ARRECIFE",
    "CATARATA",
    "CISTERNA",
    "CORRENTE",
    "EMBALSES",
    "ESTANQUE",
    "HUMEDAIS",
    "HUMIDADE",
    "MARISMAS",
    "OCEANICO",
    "REMOLINO",
    "TORRENTE",
    // 9-letter
    "AFLUENTES",
    "AGUACEIRO",
    "CATARATAS",
    "CORRENTES",
    "MANANCIAL",
    "NAVEGAVEL",
    "REMOLINOS",
  ],
  mountains: [
    // 3-letter
    "GEO",
    "RIO",
    // 4-letter
    "ALTO",
    "CIMO",
    "GELO",
    "LAGO",
    "NEVE",
    "PICO",
    "ROTA",
    "VALE",
    // 5-letter
    "CAMPO",
    "CLIMA",
    "FAUNA",
    "FLORA",
    "GRUTA",
    "MORRO",
    "NUVEM",
    "PEDRA",
    "PISTA",
    "PRADO",
    "ROCHA",
    "SENDA",
    "SERRA",
    "VENTO",
    "VISTA",
    // 6-letter
    "ABISMO",
    "ALPINO",
    "BOSQUE",
    "COLINA",
    "CRISTA",
    "RAVINA",
    "TRILHA",
    "TRILHO",
    // 7-letter
    "CASCATA",
    "CAVERNA",
    "GELEIRA",
    "GRANITO",
    "LADEIRA",
    "NEBLINA",
    "ROCHEDO",
    // 8-letter
    "ALTITUDE",
    "ESCALADA",
    "MONTANHA",
    "PAISAGEM",
    "PENHASCO",
    "PINHEIRO",
    "PLANALTO",
    // 9-letter
    "ALPINISMO",
    "AVALANCHE",
  ],
  seafood: [
    // 3-letter
    "MAR",
    "SAL",
    // 4-letter
    "ATUM",
    "LULA",
    "SIRI",
    // 5-letter
    "CORAL",
    "GAMBA",
    "OSTRA",
    "PARGO",
    "PEIXE",
    "PESCA",
    "POLVO",
    "TRUTA",
    // 6-letter
    "AMEJOA",
    "CAVIAR",
    "CHERNE",
    "ENGUIA",
    "ROBALO",
    "SALMAO",
    "TAINHA",
    "VIEIRA",
    // 7-letter
    "ANCHOVA",
    "CAMARAO",
    "CORVINA",
    "DOURADA",
    "GAROUPA",
    "LAGOSTA",
    "MARISCO",
    "PERCEBE",
    "PESCADA",
    // 8-letter
    "BACALHAU",
    "BERBIGAO",
    "LAGOSTIM",
    "LINGUADO",
    "MEXILHAO",
    "SARDINHA",
  ],
  camping: [
    // 3-letter
    "FOG",
    "LUA",
    "RIO",
    "SOL",
    // 4-letter
    "BOTE",
    "FACA",
    "FOGO",
    "LAGO",
    "MAPA",
    "REDE",
    "SACO",
    // 5-letter
    "BRASA",
    "CANOA",
    "CORDA",
    "LENHA",
    "MONTE",
    "NOITE",
    "PEIXE",
    "PESCA",
    "TENDA",
    // 6-letter
    "TRILHO",
    // 7-letter
    "ACAMPAR",
    "BARRACA",
    "CAIAQUE",
    "ESTRELA",
    "MOCHILA",
    // 8-letter
    "AVENTURA",
    "FLORESTA",
    "FOGUEIRA",
    "LANTERNA",
    "NATUREZA",
    // 9-letter
    "CAMINHADA",
  ],
  circus: [
    // 4-letter
    "ANEL",
    "BOLA",
    "CAPA",
    "LEAO",
    "LONA",
    "REDE",
    "RISO",
    "SHOW",
    "URSO",
    // 5-letter
    "CIRCO",
    "CORDA",
    "JAULA",
    "MAGIA",
    "PALCO",
    "PISTA",
    "SALTO",
    "TENDA",
    "TIGRE",
    // 6-letter
    "ILUSAO",
    "MAGICO",
    "NUMERO",
    "TRUQUE",
    // 7-letter
    "ARTISTA",
    "BILHETE",
    "CHICOTE",
    "DOMADOR",
    "ENTRADA",
    "MALABAR",
    "PALHACO",
    "PIRUETA",
    "PLATEIA",
    // 8-letter
    "ACROBATA",
    "ELEFANTE",
    "TRAPEZIO",
    // 9-letter
    "ACROBACIA",
  ],
  pirates: [
    // 3-letter
    "MAR",
    "RUM",
    // 4-letter
    "BOTE",
    "ILHA",
    "MAPA",
    "OURO",
    "REMO",
    "VELA",
    // 5-letter
    "BARCO",
    "COFRE",
    "FAROL",
    "FLOTA",
    "FROTA",
    "MARIN",
    "MOTIM",
    "NAVIO",
    "SABRE",
    // 6-letter
    "ESPADA",
    "MASTRO",
    "OCEANO",
    "PIRATA",
    // 7-letter
    "RESGATE",
    "TESOURO",
    // 8-letter
    "AVENTURA",
    "BANDEIRA",
    "PILHAGEM",
    // 9-letter
    "ABORDAGEM",
    "BUCANEIRO",
  ],
  castle: [
    // 3-letter
    "REI",
    // 4-letter
    "ARCO",
    "BOBO",
    "DAMA",
    "MAGO",
    // 5-letter
    "BISPO",
    "COROA",
    "DUQUE",
    "FOSSA",
    "FOSSO",
    "LANCE",
    "LORDE",
    "NOBRE",
    "PAJEM",
    "REINO",
    "SERVO",
    "TORRE",
    "TRONO",
    // 6-letter
    "ESPADA",
    "FESTIM",
    "FEUDAL",
    "GUARDA",
    "RAINHA",
    "SENHOR",
    // 7-letter
    "BATALHA",
    "CASTELO",
    "CRUZADA",
    "HERALDO",
    "MURALHA",
    "TORNEIO",
    "VASSALO",
    // 8-letter
    "ALQUIMIA",
    "ARMADURA",
    "BANDEIRA",
    "BANQUETE",
    "CIDADELA",
    "MASMORRA",
    "MEDIEVAL",
    "PRINCESA",
    // 9-letter
    "CATAPULTA",
    "CAVALEIRO",
    "FORTALEZA",
  ],
  jungle: [
    // 3-letter
    "AVE",
    "BOA",
    "SOL",
    // 4-letter
    "COPA",
    "LODO",
    "RAIZ",
    "SAPO",
    // 5-letter
    "BAMBU",
    "CALOR",
    "COBRA",
    "DENSO",
    "FAUNA",
    "FLORA",
    "FOLHA",
    "LIANA",
    "SELVA",
    "TIGRE",
    "VERDE",
    // 6-letter
    "GORILA",
    "IGUANA",
    "INSETO",
    "JAGUAR",
    "MACACO",
    "MANGUE",
    "PLANTA",
    "TUCANO",
    // 7-letter
    "HABITAT",
    "PANTERA",
    "PIRANHA",
    // 8-letter
    "ANACONDA",
    "ECOLOGIA",
    "FLORESTA",
    "FOLHAGEM",
    "LEOPARDO",
    "PALMEIRA",
    "PAPAGAIO",
    "SERPENTE",
    "TROPICAL",
    // 9-letter
    "CROCODILO",
  ],
  desert: [
    // 3-letter
    "SOL",
    // 4-letter
    "DUNA",
    "SECA",
    "SECO",
    "SEDE",
    // 5-letter
    "AREIA",
    "ARIDO",
    "CACTO",
    "CALOR",
    "CLIMA",
    "OASIS",
    "PALMA",
    "PEDRA",
    "ROCHA",
    "SAARA",
    "VENTO",
    // 6-letter
    "ABUTRE",
    "CAMELO",
    "CANYON",
    "COIOTE",
    "ESTEPE",
    "NOMADE",
    "POEIRA",
    "RAVINA",
    "SECURA",
    // 7-letter
    "BEDUINO",
    "DESERTO",
    "ESPINHO",
    "LAGARTO",
    "MIRAGEM",
    "TORRIDO",
    // 8-letter
    "CARAVANA",
    "SERPENTE",
    // 9-letter
    "ESCORPIAO",
    "HORIZONTE",
  ],
  arctic: [
    // 3-letter
    "SOL",
    // 4-letter
    "FOCA",
    "FRIO",
    "GELO",
    "IGLU",
    "NEVE",
    "ORCA",
    "RENA",
    "URSO",
    // 5-letter
    "HUSKY",
    "INUIT",
    "MORSA",
    "NORTE",
    "POLAR",
    "VENTO",
    // 6-letter
    "AURORA",
    "BALEIA",
    "CARIBU",
    "GELADO",
    "NARVAL",
    "TUNDRA",
    // 7-letter
    "GELEIRA",
    "ICEBERG",
    "PINGUIM",
    // 8-letter
    "BLIZZARD",
    // 9-letter
    "AVALANCHE",
    "CONGELADO",
  ],
  carnival: [
    // 3-letter
    "REI",
    "RUA",
    // 4-letter
    "TRIO",
    // 5-letter
    "ABADA",
    "BAILE",
    "BANDA",
    "BLOCO",
    "CARRO",
    "FESTA",
    "FOLIA",
    "FREVO",
    "RITMO",
    "SAMBA",
    // 6-letter
    "BRILHO",
    "ESCOLA",
    "JUBILO",
    "MUSICA",
    "PLUMAS",
    "RAINHA",
    // 7-letter
    "ALEGRIA",
    "AVENIDA",
    "BATERIA",
    "CONFETE",
    "CORTEJO",
    "DESFILE",
    "GLITTER",
    "MASCARA",
    "MELODIA",
    "ZABUMBA",
    // 8-letter
    "CAMAROTE",
    "CARNAVAL",
    "FANTASIA",
    "FESTIVAL",
    "FOLCLORE",
    "PANDEIRO",
    "PASSISTA",
    "SAMBISTA",
  ],
};
