/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DailyPuzzleInfo {
    seed: bigint;
    level: bigint;
    alreadyCompleted: boolean;
    themeId: ThemeId;
}
export type ThemeId = string;
export interface CurrentPuzzle {
    grid: Array<Array<string>>;
    puzzleIndex: bigint;
    foundWords: Array<string>;
    words: Array<string>;
    hintsUsed: bigint;
    themeId: ThemeId;
}
export interface UserProgress {
    hints: bigint;
    coins: bigint;
    currentPuzzle?: CurrentPuzzle;
    themeProgress: Array<[ThemeId, bigint]>;
    lastHintRegenTime: bigint;
    lastDailyCompletion: bigint;
}
export interface UserProfile {
    name: string;
}
export interface backendInterface {
    buyHint(): Promise<void>;
    checkAuth(): Promise<boolean>;
    clearCurrentPuzzle(): Promise<void>;
    completeDailyPuzzle(hintsUsed: bigint): Promise<bigint>;
    completePuzzle(hintsUsed: bigint, timedCompletion: boolean): Promise<boolean>;
    getDailyPuzzle(): Promise<DailyPuzzleInfo>;
    getProfile(): Promise<UserProfile | null>;
    getProgress(): Promise<UserProgress>;
    saveFoundWord(word: string): Promise<void>;
    setProfile(name: string): Promise<void>;
    startPuzzle(themeId: ThemeId, puzzleIndex: bigint, grid: Array<Array<string>>, words: Array<string>): Promise<void>;
    useHint(): Promise<void>;
}
import type { CurrentPuzzle as _CurrentPuzzle, ThemeId as _ThemeId, UserProfile as _UserProfile, UserProgress as _UserProgress } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async buyHint(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.buyHint();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buyHint();
            return result;
        }
    }
    async checkAuth(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAuth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAuth();
            return result;
        }
    }
    async clearCurrentPuzzle(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCurrentPuzzle();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCurrentPuzzle();
            return result;
        }
    }
    async completeDailyPuzzle(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.completeDailyPuzzle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeDailyPuzzle(arg0);
            return result;
        }
    }
    async completePuzzle(arg0: bigint, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completePuzzle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completePuzzle(arg0, arg1);
            return result;
        }
    }
    async getDailyPuzzle(): Promise<DailyPuzzleInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyPuzzle();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyPuzzle();
            return result;
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgress(): Promise<UserProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress();
                return from_candid_UserProgress_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress();
            return from_candid_UserProgress_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveFoundWord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFoundWord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFoundWord(arg0);
            return result;
        }
    }
    async setProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0);
            return result;
        }
    }
    async startPuzzle(arg0: ThemeId, arg1: bigint, arg2: Array<Array<string>>, arg3: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startPuzzle(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startPuzzle(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async useHint(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.useHint();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.useHint();
            return result;
        }
    }
}
function from_candid_UserProgress_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProgress): UserProgress {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CurrentPuzzle]): CurrentPuzzle | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hints: bigint;
    coins: bigint;
    currentPuzzle: [] | [_CurrentPuzzle];
    themeProgress: Array<[_ThemeId, bigint]>;
    lastHintRegenTime: bigint;
    lastDailyCompletion: bigint;
}): {
    hints: bigint;
    coins: bigint;
    currentPuzzle?: CurrentPuzzle;
    themeProgress: Array<[ThemeId, bigint]>;
    lastHintRegenTime: bigint;
    lastDailyCompletion: bigint;
} {
    return {
        hints: value.hints,
        coins: value.coins,
        currentPuzzle: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.currentPuzzle)),
        themeProgress: value.themeProgress,
        lastHintRegenTime: value.lastHintRegenTime,
        lastDailyCompletion: value.lastDailyCompletion
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
