/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ThemeId = IDL.Text;
export const DailyPuzzleInfo = IDL.Record({
  'seed' : IDL.Nat,
  'level' : IDL.Nat,
  'alreadyCompleted' : IDL.Bool,
  'themeId' : ThemeId,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CurrentPuzzle = IDL.Record({
  'grid' : IDL.Vec(IDL.Vec(IDL.Text)),
  'puzzleIndex' : IDL.Nat,
  'foundWords' : IDL.Vec(IDL.Text),
  'words' : IDL.Vec(IDL.Text),
  'hintsUsed' : IDL.Nat,
  'themeId' : ThemeId,
});
export const UserProgress = IDL.Record({
  'hints' : IDL.Nat,
  'coins' : IDL.Nat,
  'currentPuzzle' : IDL.Opt(CurrentPuzzle),
  'themeProgress' : IDL.Vec(IDL.Tuple(ThemeId, IDL.Nat)),
  'lastHintRegenTime' : IDL.Int,
  'lastDailyCompletion' : IDL.Int,
});

export const idlService = IDL.Service({
  'buyHint' : IDL.Func([], [], []),
  'checkAuth' : IDL.Func([], [IDL.Bool], ['query']),
  'clearCurrentPuzzle' : IDL.Func([], [], []),
  'completeDailyPuzzle' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'completePuzzle' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'getDailyPuzzle' : IDL.Func([], [DailyPuzzleInfo], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getProgress' : IDL.Func([], [UserProgress], ['query']),
  'saveFoundWord' : IDL.Func([IDL.Text], [], []),
  'setProfile' : IDL.Func([IDL.Text], [], []),
  'startPuzzle' : IDL.Func(
      [ThemeId, IDL.Nat, IDL.Vec(IDL.Vec(IDL.Text)), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'useHint' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ThemeId = IDL.Text;
  const DailyPuzzleInfo = IDL.Record({
    'seed' : IDL.Nat,
    'level' : IDL.Nat,
    'alreadyCompleted' : IDL.Bool,
    'themeId' : ThemeId,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CurrentPuzzle = IDL.Record({
    'grid' : IDL.Vec(IDL.Vec(IDL.Text)),
    'puzzleIndex' : IDL.Nat,
    'foundWords' : IDL.Vec(IDL.Text),
    'words' : IDL.Vec(IDL.Text),
    'hintsUsed' : IDL.Nat,
    'themeId' : ThemeId,
  });
  const UserProgress = IDL.Record({
    'hints' : IDL.Nat,
    'coins' : IDL.Nat,
    'currentPuzzle' : IDL.Opt(CurrentPuzzle),
    'themeProgress' : IDL.Vec(IDL.Tuple(ThemeId, IDL.Nat)),
    'lastHintRegenTime' : IDL.Int,
    'lastDailyCompletion' : IDL.Int,
  });
  
  return IDL.Service({
    'buyHint' : IDL.Func([], [], []),
    'checkAuth' : IDL.Func([], [IDL.Bool], ['query']),
    'clearCurrentPuzzle' : IDL.Func([], [], []),
    'completeDailyPuzzle' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'completePuzzle' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'getDailyPuzzle' : IDL.Func([], [DailyPuzzleInfo], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getProgress' : IDL.Func([], [UserProgress], ['query']),
    'saveFoundWord' : IDL.Func([IDL.Text], [], []),
    'setProfile' : IDL.Func([IDL.Text], [], []),
    'startPuzzle' : IDL.Func(
        [ThemeId, IDL.Nat, IDL.Vec(IDL.Vec(IDL.Text)), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'useHint' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };