/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CurrentPuzzle {
  'grid' : Array<Array<string>>,
  'puzzleIndex' : bigint,
  'foundWords' : Array<string>,
  'words' : Array<string>,
  'hintsUsed' : bigint,
  'themeId' : ThemeId,
}
export interface DailyPuzzleInfo {
  'seed' : bigint,
  'level' : bigint,
  'alreadyCompleted' : boolean,
  'themeId' : ThemeId,
}
export type ThemeId = string;
export interface UserProfile { 'name' : string }
export interface UserProgress {
  'hints' : bigint,
  'coins' : bigint,
  'currentPuzzle' : [] | [CurrentPuzzle],
  'themeProgress' : Array<[ThemeId, bigint]>,
  'lastHintRegenTime' : bigint,
  'lastDailyCompletion' : bigint,
}
export interface _SERVICE {
  'buyHint' : ActorMethod<[], undefined>,
  'checkAuth' : ActorMethod<[], boolean>,
  'clearCurrentPuzzle' : ActorMethod<[], undefined>,
  'completeDailyPuzzle' : ActorMethod<[bigint], bigint>,
  'completePuzzle' : ActorMethod<[bigint, boolean], boolean>,
  'getDailyPuzzle' : ActorMethod<[], DailyPuzzleInfo>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getProgress' : ActorMethod<[], UserProgress>,
  'saveFoundWord' : ActorMethod<[string], undefined>,
  'setProfile' : ActorMethod<[string], undefined>,
  'startPuzzle' : ActorMethod<
    [ThemeId, bigint, Array<Array<string>>, Array<string>],
    undefined
  >,
  'useHint' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];